var ReferencePokemon = {
  pokemonReferenceArray:[ { id: 1,
      name: 'BULBASAUR',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 118,
      baseDefense: 118,
      baseHP: 90,
      possibleFM: [ 'TACKLE', 'VINE WHIP' ],
      possibleCM: [ 'POWER WHIP', 'SEED BOMB', 'SLUDGE BOMB' ]},
    { id: 2,
      name: 'IVYSAUR',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 151,
      baseDefense: 151,
      baseHP: 120,
      possibleFM: [ 'VINE WHIP', 'RAZOR LEAF' ],
      possibleCM: [ 'POWER WHIP', 'SOLAR BEAM', 'SLUDGE BOMB' ] },
    { id: 3,
      name: 'VENUSAUR',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 198,
      baseDefense: 198,
      baseHP: 160,
      possibleFM: [ 'VINE WHIP', 'RAZOR LEAF' ],
      possibleCM: [ 'SOLAR BEAM', 'PETAL BLIZZARD', 'SLUDGE BOMB' ] },
    { id: 4,
      name: 'CHARMANDER',
      type1: 'FIRE',
      type2: '',
      baseAttack: 116,
      baseDefense: 96,
      baseHP: 78,
      possibleFM: [ 'SCRATCH', 'EMBER' ],
      possibleCM: [ 'FLAMETHROWER', 'FLAME BURST', 'FLAME CHARGE' ] },
    { id: 5,
      name: 'CHARMELEON',
      type1: 'FIRE',
      type2: '',
      baseAttack: 158,
      baseDefense: 129,
      baseHP: 116,
      possibleFM: [ 'FIRE FANG', 'EMBER' ],
      possibleCM: [ 'FLAMETHROWER', 'FLAME BURST', 'FIRE PUNCH' ] },
    { id: 6,
      name: 'CHARIZARD',
      type1: 'FIRE',
      type2: 'FLYING',
      baseAttack: 223,
      baseDefense: 176,
      baseHP: 156,
      possibleFM: [ 'AIR SLASH', 'FIRE SPIN' ],
      possibleCM: [ 'OVERHEAT', 'DRAGON CLAW', 'FIRE BLAST' ] },
    { id: 7,
      name: 'SQUIRTLE',
      type1: 'WATER',
      type2: '',
      baseAttack: 94,
      baseDefense: 122,
      baseHP: 88,
      possibleFM: [ 'TACKLE', 'BUBBLE' ],
      possibleCM: [ 'WATER PULSE', 'AQUA TAIL', 'AQUA JET' ] },
    { id: 8,
      name: 'WARTORTLE',
      type1: 'WATER',
      type2: '',
      baseAttack: 126,
      baseDefense: 155,
      baseHP: 118,
      possibleFM: [ 'BITE', 'WATER GUN' ],
      possibleCM: [ 'HYDRO PUMP', 'ICE BEAM', 'AQUA JET' ] },
    { id: 9,
      name: 'BLASTOISE',
      type1: 'WATER',
      type2: '',
      baseAttack: 171,
      baseDefense: 210,
      baseHP: 158,
      possibleFM: [ 'BITE', 'WATER GUN' ],
      possibleCM: [ 'HYDRO PUMP', 'ICE BEAM', 'FLASH CANNON' ] },
    { id: 10,
      name: 'CATERPIE',
      type1: 'BUG',
      type2: '',
      baseAttack: 55,
      baseDefense: 62,
      baseHP: 90,
      possibleFM: [ 'TACKLE', 'BUG BITE' ],
      possibleCM: [ 'STRUGGLE' ] },
    { id: 11,
      name: 'METAPOD',
      type1: 'BUG',
      type2: '',
      baseAttack: 45,
      baseDefense: 94,
      baseHP: 100,
      possibleFM: [ 'TACKLE', 'BUG BITE' ],
      possibleCM: [ 'STRUGGLE' ] },
    { id: 12,
      name: 'BUTTERFREE',
      type1: 'BUG',
      type2: 'FLYING',
      baseAttack: 167,
      baseDefense: 151,
      baseHP: 120,
      possibleFM: [ 'CONFUSION', 'STRUGGLE BUG' ],
      possibleCM: [ 'SIGNAL BEAM', 'PSYCHIC', 'BUG BUZZ' ] },
    { id: 13,
      name: 'WEEDLE',
      type1: 'BUG',
      type2: 'POISON',
      baseAttack: 63,
      baseDefense: 55,
      baseHP: 80,
      possibleFM: [ 'POISON STING', 'BUG BITE' ],
      possibleCM: [ 'STRUGGLE' ] },
    { id: 14,
      name: 'KAKUNA',
      type1: 'BUG',
      type2: 'POISON',
      baseAttack: 46,
      baseDefense: 86,
      baseHP: 90,
      possibleFM: [ 'POISON STING', 'BUG BITE' ],
      possibleCM: [ 'STRUGGLE' ] },
    { id: 15,
      name: 'BEEDRILL',
      type1: 'BUG',
      type2: 'POISON',
      baseAttack: 169,
      baseDefense: 150,
      baseHP: 130,
      possibleFM: [ 'POISON JAB', 'INFESTATION' ],
      possibleCM: [ 'X SCISSOR', 'AERIAL ACE', 'SLUDGE BOMB' ] },
    { id: 16,
      name: 'PIDGEY',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 85,
      baseDefense: 76,
      baseHP: 80,
      possibleFM: [ 'TACKLE', 'QUICK ATTACK' ],
      possibleCM: [ 'AIR CUTTER', 'AERIAL ACE', 'TWISTER' ] },
    { id: 17,
      name: 'PIDGEOTTO',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 117,
      baseDefense: 108,
      baseHP: 126,
      possibleFM: [ 'STEEL WING', 'WING ATTACK' ],
      possibleCM: [ 'AIR CUTTER', 'AERIAL ACE', 'TWISTER' ] },
    { id: 18,
      name: 'PIDGEOT',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 166,
      baseDefense: 157,
      baseHP: 166,
      possibleFM: [ 'STEEL WING', 'AIR SLASH' ],
      possibleCM: [ 'BRAVE BIRD', 'AERIAL ACE', 'HURRICANE' ] },
    { id: 19,
      name: 'RATTATA',
      type1: 'NORMAL',
      type2: '',
      baseAttack: 103,
      baseDefense: 70,
      baseHP: 60,
      possibleFM: [ 'QUICK ATTACK', 'TACKLE' ],
      possibleCM: [ 'BODY SLAM', 'HYPER FANG', 'DIG' ] },
    { id: 20,
      name: 'RATICATE',
      type1: 'NORMAL',
      type2: '',
      baseAttack: 161,
      baseDefense: 144,
      baseHP: 110,
      possibleFM: [ 'QUICK ATTACK', 'BITE' ],
      possibleCM: [ 'HYPER BEAM', 'HYPER FANG', 'DIG' ] },
    { id: 21,
      name: 'SPEAROW',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 112,
      baseDefense: 61,
      baseHP: 80,
      possibleFM: [ 'QUICK ATTACK', 'PECK' ],
      possibleCM: [ 'SKY ATTACK', 'DRILL PECK', 'AERIAL ACE' ] },
    { id: 22,
      name: 'FEAROW',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 182,
      baseDefense: 135,
      baseHP: 130,
      possibleFM: [ 'STEEL WING', 'PECK' ],
      possibleCM: [ 'SKY ATTACK', 'DRILL RUN', 'AERIAL ACE' ] },
    { id: 23,
      name: 'EKANS',
      type1: 'POISON',
      type2: '',
      baseAttack: 110,
      baseDefense: 102,
      baseHP: 70,
      possibleFM: [ 'ACID', 'POISON STING' ],
      possibleCM: [ 'SLUDGE BOMB', 'POISON FANG', 'WRAP' ] },
    { id: 24,
      name: 'ARBOK',
      type1: 'POISON',
      type2: '',
      baseAttack: 167,
      baseDefense: 158,
      baseHP: 120,
      possibleFM: [ 'ACID', 'BITE' ],
      possibleCM: [ 'GUNK SHOT', 'SLUDGE WAVE', 'DARK PULSE' ] },
    { id: 25,
      name: 'PIKACHU',
      type1: 'ELECTRIC',
      type2: '',
      baseAttack: 112,
      baseDefense: 101,
      baseHP: 70,
      possibleFM: [ 'QUICK ATTACK', 'THUNDER SHOCK' ],
      possibleCM: [ 'WILD CHARGE', 'THUNDERBOLT', 'DISCHARGE' ] },
    { id: 26,
      name: 'RAICHU',
      type1: 'ELECTRIC',
      type2: '',
      baseAttack: 193,
      baseDefense: 165,
      baseHP: 120,
      possibleFM: [ 'SPARK', 'VOLT SWITCH' ],
      possibleCM: [ 'WILD CHARGE', 'THUNDER PUNCH', 'BRICK BREAK' ] },
    { id: 27,
      name: 'SANDSHREW',
      type1: 'GROUND',
      type2: '',
      baseAttack: 126,
      baseDefense: 145,
      baseHP: 100,
      possibleFM: [ 'MUD SHOT', 'SCRATCH' ],
      possibleCM: [ 'SAND TOMB', 'ROCK SLIDE', 'DIG' ] },
    { id: 28,
      name: 'SANDSLASH',
      type1: 'GROUND',
      type2: '',
      baseAttack: 182,
      baseDefense: 202,
      baseHP: 150,
      possibleFM: [ 'MUD SHOT', 'METAL CLAW' ],
      possibleCM: [ 'BULLDOZE', 'ROCK TOMB', 'EARTHQUAKE' ] },
    { id: 29,
      name: 'NIDORAN_FEMALE',
      type1: 'POISON',
      type2: '',
      baseAttack: 86,
      baseDefense: 94,
      baseHP: 110,
      possibleFM: [ 'POISON STING', 'BITE' ],
      possibleCM: [ 'SLUDGE BOMB', 'BODY SLAM', 'POISON FANG' ] },
    { id: 30,
      name: 'NIDORINA',
      type1: 'POISON',
      type2: '',
      baseAttack: 117,
      baseDefense: 126,
      baseHP: 140,
      possibleFM: [ 'POISON STING', 'BITE' ],
      possibleCM: [ 'SLUDGE BOMB', 'DIG', 'POISON FANG' ] },
    { id: 31,
      name: 'NIDOQUEEN',
      type1: 'POISON',
      type2: 'GROUND',
      baseAttack: 180,
      baseDefense: 174,
      baseHP: 180,
      possibleFM: [ 'BITE', 'POISON JAB' ],
      possibleCM: [ 'STONE EDGE', 'SLUDGE WAVE', 'EARTHQUAKE' ] },
    { id: 32,
      name: 'NIDORAN_MALE',
      type1: 'POISON',
      type2: '',
      baseAttack: 105,
      baseDefense: 76,
      baseHP: 92,
      possibleFM: [ 'POISON STING', 'PECK' ],
      possibleCM: [ 'SLUDGE BOMB', 'BODY SLAM', 'HORN ATTACK' ] },
    { id: 33,
      name: 'NIDORINO',
      type1: 'POISON',
      type2: '',
      baseAttack: 137,
      baseDefense: 112,
      baseHP: 122,
      possibleFM: [ 'POISON STING', 'POISON JAB' ],
      possibleCM: [ 'SLUDGE BOMB', 'DIG', 'HORN ATTACK' ] },
    { id: 34,
      name: 'NIDOKING',
      type1: 'POISON',
      type2: 'GROUND',
      baseAttack: 204,
      baseDefense: 157,
      baseHP: 162,
      possibleFM: [ 'IRON TAIL', 'POISON JAB' ],
      possibleCM: [ 'MEGAHORN', 'SLUDGE WAVE', 'EARTHQUAKE' ] },
    { id: 35,
      name: 'CLEFAIRY',
      type1: 'FAIRY',
      type2: '',
      baseAttack: 107,
      baseDefense: 116,
      baseHP: 140,
      possibleFM: [ 'ZEN HEADBUTT', 'POUND' ],
      possibleCM: [ 'MOONBLAST', 'BODY SLAM', 'DISARMING VOICE' ] },
    { id: 36,
      name: 'CLEFABLE',
      type1: 'FAIRY',
      type2: '',
      baseAttack: 178,
      baseDefense: 171,
      baseHP: 190,
      possibleFM: [ 'ZEN HEADBUTT', 'CHARGE BEAM' ],
      possibleCM: [ 'MOONBLAST', 'PSYCHIC', 'DAZZLING GLEAM' ] },
    { id: 37,
      name: 'VULPIX',
      type1: 'FIRE',
      type2: '',
      baseAttack: 96,
      baseDefense: 122,
      baseHP: 76,
      possibleFM: [ 'EMBER', 'QUICK ATTACK' ],
      possibleCM: [ 'FLAME CHARGE', 'FLAMETHROWER', 'BODY SLAM' ] },
    { id: 38,
      name: 'NINETALES',
      type1: 'FIRE',
      type2: '',
      baseAttack: 169,
      baseDefense: 204,
      baseHP: 146,
      possibleFM: [ 'FIRE SPIN', 'FEINT ATTACK' ],
      possibleCM: [ 'SOLAR BEAM', 'OVERHEAT', 'HEAT WAVE' ] },
    { id: 39,
      name: 'JIGGLYPUFF',
      type1: 'NORMAL',
      type2: 'FAIRY',
      baseAttack: 80,
      baseDefense: 44,
      baseHP: 230,
      possibleFM: [ 'FEINT ATTACK', 'POUND' ],
      possibleCM: [ 'DAZZLING GLEAM', 'GYRO BALL', 'DISARMING VOICE' ] },
    { id: 40,
      name: 'WIGGLYTUFF',
      type1: 'NORMAL',
      type2: 'FAIRY',
      baseAttack: 156,
      baseDefense: 93,
      baseHP: 280,
      possibleFM: [ 'FEINT ATTACK', 'POUND' ],
      possibleCM: [ 'PLAY ROUGH', 'HYPER BEAM', 'DAZZLING GLEAM' ] },
    { id: 41,
      name: 'ZUBAT',
      type1: 'POISON',
      type2: 'FLYING',
      baseAttack: 83,
      baseDefense: 76,
      baseHP: 80,
      possibleFM: [ 'BITE', 'QUICK ATTACK' ],
      possibleCM: [ 'SWIFT', 'AIR CUTTER', 'POISON FANG' ] },
    { id: 42,
      name: 'GOLBAT',
      type1: 'POISON',
      type2: 'FLYING',
      baseAttack: 161,
      baseDefense: 153,
      baseHP: 150,
      possibleFM: [ 'BITE', 'WING ATTACK' ],
      possibleCM: [ 'POISON FANG', 'AIR CUTTER', 'SHADOW BALL' ] },
    { id: 43,
      name: 'ODDISH',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 131,
      baseDefense: 116,
      baseHP: 90,
      possibleFM: [ 'ACID', 'RAZOR LEAF' ],
      possibleCM: [ 'MOONBLAST', 'SLUDGE BOMB', 'SEED BOMB' ] },
    { id: 44,
      name: 'GLOOM',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 153,
      baseDefense: 139,
      baseHP: 120,
      possibleFM: [ 'ACID', 'RAZOR LEAF' ],
      possibleCM: [ 'MOONBLAST', 'SLUDGE BOMB', 'PETAL BLIZZARD' ] },
    { id: 45,
      name: 'VILEPLUME',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 202,
      baseDefense: 170,
      baseHP: 150,
      possibleFM: [ 'ACID', 'RAZOR LEAF' ],
      possibleCM: [ 'MOONBLAST', 'SOLAR BEAM', 'PETAL BLIZZARD' ] },
    { id: 46,
      name: 'PARAS',
      type1: 'BUG',
      type2: 'GRASS',
      baseAttack: 121,
      baseDefense: 99,
      baseHP: 70,
      possibleFM: [ 'BUG BITE', 'SCRATCH' ],
      possibleCM: [ 'SEED BOMB', 'X SCISSOR', 'CROSS POISON' ] },
    { id: 47,
      name: 'PARASECT',
      type1: 'BUG',
      type2: 'GRASS',
      baseAttack: 165,
      baseDefense: 146,
      baseHP: 120,
      possibleFM: [ 'FURY CUTTER', 'STRUGGLE BUG' ],
      possibleCM: [ 'SOLAR BEAM', 'X SCISSOR', 'CROSS POISON' ] },
    { id: 48,
      name: 'VENONAT',
      type1: 'BUG',
      type2: 'POISON',
      baseAttack: 100,
      baseDefense: 102,
      baseHP: 120,
      possibleFM: [ 'CONFUSION', 'BUG BITE' ],
      possibleCM: [ 'SIGNAL BEAM', 'PSYBEAM', 'POISON FANG' ] },
    { id: 49,
      name: 'VENOMOTH',
      type1: 'BUG',
      type2: 'POISON',
      baseAttack: 179,
      baseDefense: 150,
      baseHP: 140,
      possibleFM: [ 'CONFUSION', 'INFESTATION' ],
      possibleCM: [ 'BUG BUZZ', 'PSYCHIC', 'SILVER WIND' ] },
    { id: 50,
      name: 'DIGLETT',
      type1: 'GROUND',
      type2: '',
      baseAttack: 109,
      baseDefense: 88,
      baseHP: 20,
      possibleFM: [ 'SCRATCH', 'MUD SLAP' ],
      possibleCM: [ 'ROCK TOMB', 'MUD BOMB', 'DIG' ] },
    { id: 51,
      name: 'DUGTRIO',
      type1: 'GROUND',
      type2: '',
      baseAttack: 167,
      baseDefense: 147,
      baseHP: 70,
      possibleFM: [ 'MUD SLAP', 'SUCKER PUNCH' ],
      possibleCM: [ 'STONE EDGE', 'MUD BOMB', 'EARTHQUAKE' ] },
    { id: 52,
      name: 'MEOWTH',
      type1: 'NORMAL',
      type2: '',
      baseAttack: 92,
      baseDefense: 81,
      baseHP: 80,
      possibleFM: [ 'BITE', 'SCRATCH' ],
      possibleCM: [ 'FOUL PLAY', 'DARK PULSE', 'NIGHT SLASH' ] },
    { id: 53,
      name: 'PERSIAN',
      type1: 'NORMAL',
      type2: '',
      baseAttack: 150,
      baseDefense: 139,
      baseHP: 130,
      possibleFM: [ 'FEINT ATTACK', 'SCRATCH' ],
      possibleCM: [ 'PLAY ROUGH', 'POWER GEM', 'FOUL PLAY' ] },
    { id: 54,
      name: 'PSYDUCK',
      type1: 'WATER',
      type2: '',
      baseAttack: 122,
      baseDefense: 96,
      baseHP: 100,
      possibleFM: [ 'ZEN HEADBUTT', 'WATER GUN' ],
      possibleCM: [ 'CROSS CHOP', 'AQUA TAIL', 'PSYBEAM' ] },
    { id: 55,
      name: 'GOLDUCK',
      type1: 'WATER',
      type2: '',
      baseAttack: 191,
      baseDefense: 163,
      baseHP: 160,
      possibleFM: [ 'CONFUSION', 'WATER GUN' ],
      possibleCM: [ 'ICE BEAM', 'HYDRO PUMP', 'PSYCHIC' ] },
    { id: 56,
      name: 'MANKEY',
      type1: 'FIGHTING',
      type2: '',
      baseAttack: 148,
      baseDefense: 87,
      baseHP: 80,
      possibleFM: [ 'SCRATCH', 'KARATE CHOP' ],
      possibleCM: [ 'BRICK BREAK', 'LOW SWEEP', 'CROSS CHOP' ] },
    { id: 57,
      name: 'PRIMEAPE',
      type1: 'FIGHTING',
      type2: '',
      baseAttack: 207,
      baseDefense: 144,
      baseHP: 130,
      possibleFM: [ 'COUNTER', 'LOW KICK' ],
      possibleCM: [ 'NIGHT SLASH', 'LOW SWEEP', 'CLOSE COMBAT' ] },
    { id: 58,
      name: 'GROWLITHE',
      type1: 'FIRE',
      type2: '',
      baseAttack: 136,
      baseDefense: 96,
      baseHP: 110,
      possibleFM: [ 'BITE', 'EMBER' ],
      possibleCM: [ 'FLAMETHROWER', 'BODY SLAM', 'FLAME WHEEL' ] },
    { id: 59,
      name: 'ARCANINE',
      type1: 'FIRE',
      type2: '',
      baseAttack: 227,
      baseDefense: 166,
      baseHP: 180,
      possibleFM: [ 'SNARL', 'FIRE FANG' ],
      possibleCM: [ 'CRUNCH', 'WILD CHARGE', 'FIRE BLAST' ] },
    { id: 60,
      name: 'POLIWAG',
      type1: 'WATER',
      type2: '',
      baseAttack: 101,
      baseDefense: 82,
      baseHP: 80,
      possibleFM: [ 'MUD SHOT', 'BUBBLE' ],
      possibleCM: [ 'BODY SLAM', 'MUD BOMB', 'BUBBLE BEAM' ] },
    { id: 61,
      name: 'POLIWHIRL',
      type1: 'WATER',
      type2: '',
      baseAttack: 130,
      baseDefense: 130,
      baseHP: 130,
      possibleFM: [ 'MUD SHOT', 'BUBBLE' ],
      possibleCM: [ 'BUBBLE BEAM', 'MUD BOMB', 'WATER PULSE' ] },
    { id: 62,
      name: 'POLIWRATH',
      type1: 'WATER',
      type2: 'FIGHTING',
      baseAttack: 182,
      baseDefense: 187,
      baseHP: 180,
      possibleFM: [ 'ROCK SMASH', 'BUBBLE' ],
      possibleCM: [ 'ICE PUNCH', 'DYNAMIC PUNCH', 'HYDRO PUMP' ] },
    { id: 63,
      name: 'ABRA',
      type1: 'PSYCHIC',
      type2: '',
      baseAttack: 195,
      baseDefense: 103,
      baseHP: 50,
      possibleFM: [ 'CHARGE BEAM', 'ZEN HEADBUTT' ],
      possibleCM: [ 'SHADOW BALL', 'SIGNAL BEAM', 'PSYSHOCK' ] },
    { id: 64,
      name: 'KADABRA',
      type1: 'PSYCHIC',
      type2: '',
      baseAttack: 232,
      baseDefense: 138,
      baseHP: 80,
      possibleFM: [ 'CONFUSION', 'PSYCHO CUT' ],
      possibleCM: [ 'SHADOW BALL', 'DAZZLING GLEAM', 'PSYBEAM' ] },
    { id: 65,
      name: 'ALAKAZAM',
      type1: 'PSYCHIC',
      type2: '',
      baseAttack: 271,
      baseDefense: 194,
      baseHP: 110,
      possibleFM: [ 'CONFUSION', 'PSYCHO CUT' ],
      possibleCM: [ 'SHADOW BALL', 'FOCUS BLAST', 'FUTURESIGHT' ] },
    { id: 66,
      name: 'MACHOP',
      type1: 'FIGHTING',
      type2: '',
      baseAttack: 137,
      baseDefense: 88,
      baseHP: 140,
      possibleFM: [ 'KARATE CHOP', 'ROCK SMASH' ],
      possibleCM: [ 'CROSS CHOP', 'BRICK BREAK', 'LOW SWEEP' ] },
    { id: 67,
      name: 'MACHOKE',
      type1: 'FIGHTING',
      type2: '',
      baseAttack: 177,
      baseDefense: 130,
      baseHP: 160,
      possibleFM: [ 'KARATE CHOP', 'LOW KICK' ],
      possibleCM: [ 'DYNAMIC PUNCH', 'BRICK BREAK', 'SUBMISSION' ] },
    { id: 68,
      name: 'MACHAMP',
      type1: 'FIGHTING',
      type2: '',
      baseAttack: 234,
      baseDefense: 162,
      baseHP: 180,
      possibleFM: [ 'COUNTER', 'BULLET PUNCH' ],
      possibleCM: [ 'CLOSE COMBAT', 'DYNAMIC PUNCH', 'HEAVY SLAM' ] },
    { id: 69,
      name: 'BELLSPROUT',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 139,
      baseDefense: 64,
      baseHP: 100,
      possibleFM: [ 'ACID', 'VINE WHIP' ],
      possibleCM: [ 'WRAP', 'SLUDGE BOMB', 'POWER WHIP' ] },
    { id: 70,
      name: 'WEEPINBELL',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 172,
      baseDefense: 95,
      baseHP: 130,
      possibleFM: [ 'ACID', 'BULLET SEED' ],
      possibleCM: [ 'SEED BOMB', 'SLUDGE BOMB', 'POWER WHIP' ] },
    { id: 71,
      name: 'VICTREEBEL',
      type1: 'GRASS',
      type2: 'POISON',
      baseAttack: 207,
      baseDefense: 138,
      baseHP: 160,
      possibleFM: [ 'ACID', 'RAZOR LEAF' ],
      possibleCM: [ 'SOLAR BEAM', 'SLUDGE BOMB', 'LEAF BLADE' ] },
    { id: 72,
      name: 'TENTACOOL',
      type1: 'WATER',
      type2: 'POISON',
      baseAttack: 97,
      baseDefense: 182,
      baseHP: 80,
      possibleFM: [ 'POISON STING', 'BUBBLE' ],
      possibleCM: [ 'WRAP', 'WATER PULSE', 'BUBBLE BEAM' ] },
    { id: 73,
      name: 'TENTACRUEL',
      type1: 'WATER',
      type2: 'POISON',
      baseAttack: 166,
      baseDefense: 237,
      baseHP: 160,
      possibleFM: [ 'POISON JAB', 'ACID' ],
      possibleCM: [ 'BLIZZARD', 'SLUDGE WAVE', 'HYDRO PUMP' ] },
    { id: 74,
      name: 'GEODUDE',
      type1: 'ROCK',
      type2: 'GROUND',
      baseAttack: 132,
      baseDefense: 163,
      baseHP: 80,
      possibleFM: [ 'TACKLE', 'ROCK THROW' ],
      possibleCM: [ 'DIG', 'ROCK TOMB', 'ROCK SLIDE' ] },
    { id: 75,
      name: 'GRAVELER',
      type1: 'ROCK',
      type2: 'GROUND',
      baseAttack: 164,
      baseDefense: 196,
      baseHP: 110,
      possibleFM: [ 'MUD SLAP', 'ROCK THROW' ],
      possibleCM: [ 'ROCK BLAST', 'STONE EDGE', 'DIG' ] },
    { id: 76,
      name: 'GOLEM',
      type1: 'ROCK',
      type2: 'GROUND',
      baseAttack: 211,
      baseDefense: 229,
      baseHP: 160,
      possibleFM: [ 'MUD SLAP', 'ROCK THROW' ],
      possibleCM: [ 'EARTHQUAKE', 'ROCK BLAST', 'STONE EDGE' ] },
    { id: 77,
      name: 'PONYTA',
      type1: 'FIRE',
      type2: '',
      baseAttack: 170,
      baseDefense: 132,
      baseHP: 100,
      possibleFM: [ 'EMBER', 'TACKLE' ],
      possibleCM: [ 'STOMP', 'FLAME WHEEL', 'FLAME CHARGE' ] },
    { id: 78,
      name: 'RAPIDASH',
      type1: 'FIRE',
      type2: '',
      baseAttack: 207,
      baseDefense: 167,
      baseHP: 130,
      possibleFM: [ 'FIRE SPIN', 'LOW KICK' ],
      possibleCM: [ 'HEAT WAVE', 'DRILL RUN', 'FIRE BLAST' ] },
    { id: 79,
      name: 'SLOWPOKE',
      type1: 'WATER',
      type2: 'PSYCHIC',
      baseAttack: 109,
      baseDefense: 109,
      baseHP: 180,
      possibleFM: [ 'CONFUSION', 'WATER GUN' ],
      possibleCM: [ 'PSYCHIC', 'PSYSHOCK', 'WATER PULSE' ] },
    { id: 80,
      name: 'SLOWBRO',
      type1: 'WATER',
      type2: 'PSYCHIC',
      baseAttack: 177,
      baseDefense: 194,
      baseHP: 190,
      possibleFM: [ 'CONFUSION', 'WATER GUN' ],
      possibleCM: [ 'ICE BEAM', 'PSYCHIC', 'WATER PULSE' ] },
    { id: 81,
      name: 'MAGNEMITE',
      type1: 'ELECTRIC',
      type2: 'STEEL',
      baseAttack: 165,
      baseDefense: 128,
      baseHP: 50,
      possibleFM: [ 'THUNDER SHOCK', 'SPARK' ],
      possibleCM: [ 'THUNDERBOLT', 'MAGNET BOMB', 'DISCHARGE' ] },
    { id: 82,
      name: 'MAGNETON',
      type1: 'ELECTRIC',
      type2: 'STEEL',
      baseAttack: 223,
      baseDefense: 182,
      baseHP: 100,
      possibleFM: [ 'CHARGE BEAM', 'SPARK' ],
      possibleCM: [ 'FLASH CANNON', 'MAGNET BOMB', 'ZAP CANNON' ] },
    { id: 83,
      name: 'FARFETCHD',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 124,
      baseDefense: 118,
      baseHP: 104,
      possibleFM: [ 'FURY CUTTER', 'AIR SLASH' ],
      possibleCM: [ 'LEAF BLADE', 'AIR CUTTER', 'AERIAL ACE' ] },
    { id: 84,
      name: 'DODUO',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 158,
      baseDefense: 88,
      baseHP: 70,
      possibleFM: [ 'QUICK ATTACK', 'PECK' ],
      possibleCM: [ 'BRAVE BIRD', 'AERIAL ACE', 'DRILL PECK' ] },
    { id: 85,
      name: 'DODRIO',
      type1: 'NORMAL',
      type2: 'FLYING',
      baseAttack: 218,
      baseDefense: 145,
      baseHP: 120,
      possibleFM: [ 'STEEL WING', 'FEINT ATTACK' ],
      possibleCM: [ 'BRAVE BIRD', 'AERIAL ACE', 'DRILL PECK' ] },
    { id: 86,
      name: 'SEEL',
      type1: 'WATER',
      type2: '',
      baseAttack: 85,
      baseDefense: 128,
      baseHP: 130,
      possibleFM: [ 'LICK', 'ICE SHARD' ],
      possibleCM: [ 'AQUA TAIL', 'ICY WIND', 'AURORA BEAM' ] },
    { id: 87,
      name: 'DEWGONG',
      type1: 'WATER',
      type2: 'ICE',
      baseAttack: 139,
      baseDefense: 184,
      baseHP: 180,
      possibleFM: [ 'IRON TAIL', 'FROST BREATH' ],
      possibleCM: [ 'BLIZZARD', 'WATER PULSE', 'AURORA BEAM' ] },
    { id: 88,
      name: 'GRIMER',
      type1: 'POISON',
      type2: '',
      baseAttack: 135,
      baseDefense: 90,
      baseHP: 160,
      possibleFM: [ 'MUD SLAP', 'POISON JAB' ],
      possibleCM: [ 'SLUDGE BOMB', 'MUD BOMB', 'SLUDGE' ] },
    { id: 89,
      name: 'MUK',
      type1: 'POISON',
      type2: '',
      baseAttack: 190,
      baseDefense: 184,
      baseHP: 210,
      possibleFM: [ 'POISON JAB', 'INFESTATION' ],
      possibleCM: [ 'SLUDGE WAVE', 'GUNK SHOT', 'DARK PULSE' ] },
    { id: 90,
      name: 'SHELLDER',
      type1: 'WATER',
      type2: '',
      baseAttack: 116,
      baseDefense: 168,
      baseHP: 60,
      possibleFM: [ 'TACKLE', 'ICE SHARD' ],
      possibleCM: [ 'ICY WIND', 'WATER PULSE', 'BUBBLE BEAM' ] },
    { id: 91,
      name: 'CLOYSTER',
      type1: 'WATER',
      type2: 'ICE',
      baseAttack: 186,
      baseDefense: 323,
      baseHP: 100,
      possibleFM: [ 'ICE SHARD', 'FROST BREATH' ],
      possibleCM: [ 'AVALANCHE', 'HYDRO PUMP', 'AURORA BEAM' ] },
    { id: 92,
      name: 'GASTLY',
      type1: 'GHOST',
      type2: 'POISON',
      baseAttack: 186,
      baseDefense: 70,
      baseHP: 60,
      possibleFM: [ 'ASTONISH', 'LICK' ],
      possibleCM: [ 'SLUDGE BOMB', 'DARK PULSE', 'NIGHT SHADE' ] },
    { id: 93,
      name: 'HAUNTER',
      type1: 'GHOST',
      type2: 'POISON',
      baseAttack: 223,
      baseDefense: 112,
      baseHP: 90,
      possibleFM: [ 'ASTONISH', 'SHADOW CLAW' ],
      possibleCM: [ 'SLUDGE BOMB', 'DARK PULSE', 'SHADOW PUNCH' ] },
    { id: 94,
      name: 'GENGAR',
      type1: 'GHOST',
      type2: 'POISON',
      baseAttack: 261,
      baseDefense: 156,
      baseHP: 120,
      possibleFM: [ 'HEX', 'SUCKER PUNCH' ],
      possibleCM: [ 'SLUDGE BOMB', 'FOCUS BLAST', 'SHADOW BALL' ] },
    { id: 95,
      name: 'ONIX',
      type1: 'ROCK',
      type2: 'GROUND',
      baseAttack: 85,
      baseDefense: 288,
      baseHP: 70,
      possibleFM: [ 'TACKLE', 'ROCK THROW' ],
      possibleCM: [ 'HEAVY SLAM', 'STONE EDGE', 'SAND TOMB' ] },
    { id: 96,
      name: 'DROWZEE',
      type1: 'PSYCHIC',
      type2: '',
      baseAttack: 89,
      baseDefense: 158,
      baseHP: 120,
      possibleFM: [ 'CONFUSION', 'POUND' ],
      possibleCM: [ 'PSYCHIC', 'PSYSHOCK', 'PSYBEAM' ] },
    { id: 97,
      name: 'HYPNO',
      type1: 'PSYCHIC',
      type2: '',
      baseAttack: 144,
      baseDefense: 215,
      baseHP: 170,
      possibleFM: [ 'CONFUSION', 'ZEN HEADBUTT' ],
      possibleCM: [ 'FOCUS BLAST', 'PSYCHIC', 'FUTURESIGHT' ] },
    { id: 98,
      name: 'KRABBY',
      type1: 'WATER',
      type2: '',
      baseAttack: 181,
      baseDefense: 156,
      baseHP: 60,
      possibleFM: [ 'MUD SHOT', 'BUBBLE' ],
      possibleCM: [ 'WATER PULSE', 'BUBBLE BEAM', 'VICE GRIP' ] },
    { id: 99,
      name: 'KINGLER',
      type1: 'WATER',
      type2: '',
      baseAttack: 240,
      baseDefense: 214,
      baseHP: 110,
      possibleFM: [ 'METAL CLAW', 'BUBBLE' ],
      possibleCM: [ 'WATER PULSE', 'X SCISSOR', 'VICE GRIP' ] },
    { id: 100,
      name: 'VOLTORB',
      type1: 'ELECTRIC',
      type2: '',
      baseAttack: 109,
      baseDefense: 114,
      baseHP: 80,
      possibleFM: [ 'TACKLE', 'SPARK' ],
      possibleCM: [ 'GYRO BALL', 'THUNDERBOLT', 'DISCHARGE' ] },
    { id: 101,
       name: 'ELECTRODE',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 173,
       baseDefense: 179,
       baseHP: 120,
       possibleFM: [ 'VOLT SWITCH', 'SPARK' ],
       possibleCM: [ 'HYPER BEAM', 'THUNDERBOLT', 'DISCHARGE' ] },
     { id: 102,
       name: 'EXEGGCUTE',
       type1: 'GRASS',
       type2: 'PSYCHIC',
       baseAttack: 107,
       baseDefense: 140,
       baseHP: 120,
       possibleFM: [ 'BULLET SEED', 'CONFUSION' ],
       possibleCM: [ 'ANCIENT POWER', 'PSYCHIC', 'SEED BOMB' ] },
     { id: 103,
       name: 'EXEGGUTOR',
       type1: 'GRASS',
       type2: 'PSYCHIC',
       baseAttack: 233,
       baseDefense: 158,
       baseHP: 190,
       possibleFM: [ 'EXTRASENSORY', 'BULLET SEED' ],
       possibleCM: [ 'SOLAR BEAM', 'PSYCHIC', 'SEED BOMB' ] },
     { id: 104,
       name: 'CUBONE',
       type1: 'GROUND',
       type2: '',
       baseAttack: 90,
       baseDefense: 165,
       baseHP: 100,
       possibleFM: [ 'ROCK SMASH', 'MUD SLAP' ],
       possibleCM: [ 'BULLDOZE', 'DIG', 'BONE CLUB' ] },
     { id: 105,
       name: 'MAROWAK',
       type1: 'GROUND',
       type2: '',
       baseAttack: 144,
       baseDefense: 200,
       baseHP: 120,
       possibleFM: [ 'ROCK SMASH', 'MUD SLAP' ],
       possibleCM: [ 'EARTHQUAKE', 'DIG', 'BONE CLUB' ] },
     { id: 106,
       name: 'HITMONLEE',
       type1: 'FIGHTING',
       type2: '',
       baseAttack: 224,
       baseDefense: 211,
       baseHP: 100,
       possibleFM: [ 'ROCK SMASH', 'LOW KICK' ],
       possibleCM: [ 'STONE EDGE', 'LOW SWEEP', 'CLOSE COMBAT' ] },
     { id: 107,
       name: 'HITMONCHAN',
       type1: 'FIGHTING',
       type2: '',
       baseAttack: 193,
       baseDefense: 212,
       baseHP: 100,
       possibleFM: [ 'COUNTER', 'BULLET PUNCH' ],
       possibleCM: [ 'CLOSE COMBAT', 'THUNDER PUNCH', 'ICE PUNCH', 'FIRE PUNCH' ] },
     { id: 108,
       name: 'LICKITUNG',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 108,
       baseDefense: 137,
       baseHP: 180,
       possibleFM: [ 'ZEN HEADBUTT', 'LICK' ],
       possibleCM: [ 'POWER WHIP', 'STOMP', 'HYPER BEAM' ] },
     { id: 109,
       name: 'KOFFING',
       type1: 'POISON',
       type2: '',
       baseAttack: 119,
       baseDefense: 164,
       baseHP: 80,
       possibleFM: [ 'INFESTATION', 'TACKLE' ],
       possibleCM: [ 'DARK PULSE', 'SLUDGE BOMB', 'SLUDGE' ] },
     { id: 110,
       name: 'WEEZING',
       type1: 'POISON',
       type2: '',
       baseAttack: 174,
       baseDefense: 221,
       baseHP: 130,
       possibleFM: [ 'INFESTATION', 'TACKLE' ],
       possibleCM: [ 'DARK PULSE', 'SHADOW BALL', 'SLUDGE BOMB' ] },
     { id: 111,
       name: 'RHYHORN',
       type1: 'GROUND',
       type2: 'ROCK',
       baseAttack: 140,
       baseDefense: 157,
       baseHP: 160,
       possibleFM: [ 'ROCK SMASH', 'MUD SLAP' ],
       possibleCM: [ 'STOMP', 'HORN ATTACK', 'BULLDOZE' ] },
     { id: 112,
       name: 'RHYDON',
       type1: 'GROUND',
       type2: 'ROCK',
       baseAttack: 222,
       baseDefense: 206,
       baseHP: 210,
       possibleFM: [ 'ROCK SMASH', 'MUD SLAP' ],
       possibleCM: [ 'STONE EDGE', 'EARTHQUAKE', 'MEGAHORN' ] },
     { id: 113,
       name: 'CHANSEY',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 60,
       baseDefense: 176,
       baseHP: 500,
       possibleFM: [ 'ZEN HEADBUTT', 'POUND' ],
       possibleCM: [ 'DAZZLING GLEAM', 'HYPER BEAM', 'PSYCHIC' ] },
     { id: 114,
       name: 'TANGELA',
       type1: 'GRASS',
       type2: '',
       baseAttack: 183,
       baseDefense: 205,
       baseHP: 130,
       possibleFM: [ 'INFESTATION', 'VINE WHIP' ],
       possibleCM: [ 'SOLAR BEAM', 'SLUDGE BOMB', 'GRASS KNOT' ] },
     { id: 115,
       name: 'KANGASKHAN',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 181,
       baseDefense: 165,
       baseHP: 210,
       possibleFM: [ 'LOW KICK', 'MUD SLAP' ],
       possibleCM: [ 'OUTRAGE', 'EARTHQUAKE', 'CRUNCH' ] },
     { id: 116,
       name: 'HORSEA',
       type1: 'WATER',
       type2: '',
       baseAttack: 129,
       baseDefense: 125,
       baseHP: 60,
       possibleFM: [ 'BUBBLE', 'WATER GUN' ],
       possibleCM: [ 'FLASH CANNON', 'DRAGON PULSE', 'BUBBLE BEAM' ] },
     { id: 117,
       name: 'SEADRA',
       type1: 'WATER',
       type2: '',
       baseAttack: 187,
       baseDefense: 182,
       baseHP: 110,
       possibleFM: [ 'DRAGON BREATH', 'WATER GUN' ],
       possibleCM: [ 'HYDRO PUMP', 'DRAGON PULSE', 'AURORA BEAM' ] },
     { id: 118,
       name: 'GOLDEEN',
       type1: 'WATER',
       type2: '',
       baseAttack: 123,
       baseDefense: 115,
       baseHP: 90,
       possibleFM: [ 'MUD SHOT', 'PECK' ],
       possibleCM: [ 'AQUA TAIL', 'HORN ATTACK', 'WATER PULSE' ] },
     { id: 119,
       name: 'SEAKING',
       type1: 'WATER',
       type2: '',
       baseAttack: 175,
       baseDefense: 154,
       baseHP: 160,
       possibleFM: [ 'POISON JAB', 'PECK' ],
       possibleCM: [ 'MEGAHORN', 'WATER PULSE', 'ICE BEAM' ] },
     { id: 120,
       name: 'STARYU',
       type1: 'WATER',
       type2: '',
       baseAttack: 137,
       baseDefense: 112,
       baseHP: 60,
       possibleFM: [ 'WATER GUN', 'TACKLE' ],
       possibleCM: [ 'POWER GEM', 'BUBBLE BEAM', 'SWIFT' ] },
     { id: 121,
       name: 'STARMIE',
       type1: 'WATER',
       type2: 'PSYCHIC',
       baseAttack: 210,
       baseDefense: 184,
       baseHP: 120,
       possibleFM: [ 'WATER GUN', 'HIDDEN POWER' ],
       possibleCM: [ 'PSYCHIC', 'POWER GEM', 'HYDRO PUMP' ] },
     { id: 122,
       name: 'MR_MIME',
       type1: 'PSYCHIC',
       type2: 'FAIRY',
       baseAttack: 192,
       baseDefense: 233,
       baseHP: 80,
       possibleFM: [ 'ZEN HEADBUTT', 'CONFUSION' ],
       possibleCM: [ 'SHADOW BALL', 'PSYCHIC', 'PSYBEAM' ] },
     { id: 123,
       name: 'SCYTHER',
       type1: 'BUG',
       type2: 'FLYING',
       baseAttack: 218,
       baseDefense: 170,
       baseHP: 140,
       possibleFM: [ 'AIR SLASH', 'FURY CUTTER' ],
       possibleCM: [ 'AERIAL ACE', 'X SCISSOR', 'NIGHT SLASH' ] },
     { id: 124,
       name: 'JYNX',
       type1: 'ICE',
       type2: 'PSYCHIC',
       baseAttack: 223,
       baseDefense: 182,
       baseHP: 130,
       possibleFM: [ 'CONFUSION', 'FROST BREATH' ],
       possibleCM: [ 'PSYSHOCK', 'AVALANCHE', 'DRAINING KISS' ] },
     { id: 125,
       name: 'ELECTABUZZ',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 198,
       baseDefense: 173,
       baseHP: 130,
       possibleFM: [ 'LOW KICK', 'THUNDER SHOCK' ],
       possibleCM: [ 'THUNDER', 'THUNDERBOLT', 'THUNDER PUNCH' ] },
     { id: 126,
       name: 'MAGMAR',
       type1: 'FIRE',
       type2: '',
       baseAttack: 206,
       baseDefense: 169,
       baseHP: 130,
       possibleFM: [ 'KARATE CHOP', 'EMBER' ],
       possibleCM: [ 'FLAMETHROWER', 'FIRE PUNCH', 'FIRE BLAST' ] },
     { id: 127,
       name: 'PINSIR',
       type1: 'BUG',
       type2: '',
       baseAttack: 238,
       baseDefense: 197,
       baseHP: 130,
       possibleFM: [ 'BUG BITE', 'ROCK SMASH' ],
       possibleCM: [ 'CLOSE COMBAT', 'X SCISSOR', 'VICE GRIP' ] },
     { id: 128,
       name: 'TAUROS',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 198,
       baseDefense: 197,
       baseHP: 150,
       possibleFM: [ 'ZEN HEADBUTT', 'TACKLE' ],
       possibleCM: [ 'EARTHQUAKE', 'IRON HEAD', 'HORN ATTACK' ] },
     { id: 129,
       name: 'MAGIKARP',
       type1: 'WATER',
       type2: '',
       baseAttack: 29,
       baseDefense: 102,
       baseHP: 40,
       possibleFM: [ 'SPLASH' ],
       possibleCM: [ 'STRUGGLE' ] },
     { id: 130,
       name: 'GYARADOS',
       type1: 'WATER',
       type2: 'FLYING',
       baseAttack: 237,
       baseDefense: 197,
       baseHP: 190,
       possibleFM: [ 'DRAGON TAIL', 'BITE' ],
       possibleCM: [ 'OUTRAGE', 'CRUNCH', 'HYDRO PUMP' ] },
     { id: 131,
       name: 'LAPRAS',
       type1: 'WATER',
       type2: 'ICE',
       baseAttack: 165,
       baseDefense: 180,
       baseHP: 260,
       possibleFM: [ 'WATER GUN', 'FROST BREATH' ],
       possibleCM: [ 'BLIZZARD', 'ICE BEAM', 'HYDRO PUMP' ] },
     { id: 132,
       name: 'DITTO',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 91,
       baseDefense: 91,
       baseHP: 96,
       possibleFM: [ 'TRANSFORM' ],
       possibleCM: [ 'STRUGGLE' ] },
     { id: 133,
       name: 'EEVEE',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 104,
       baseDefense: 121,
       baseHP: 110,
       possibleFM: [ 'TACKLE', 'QUICK ATTACK' ],
       possibleCM: [ 'SWIFT', 'DIG' ] },
     { id: 134,
       name: 'VAPOREON',
       type1: 'WATER',
       type2: '',
       baseAttack: 205,
       baseDefense: 177,
       baseHP: 260,
       possibleFM: [ 'WATER GUN' ],
       possibleCM: [ 'AQUA TAIL', 'HYDRO PUMP', 'WATER PULSE' ] },
     { id: 135,
       name: 'JOLTEON',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 232,
       baseDefense: 201,
       baseHP: 130,
       possibleFM: [ 'VOLT SWITCH', 'THUNDER SHOCK' ],
       possibleCM: [ 'THUNDER', 'THUNDERBOLT', 'DISCHARGE' ] },
     { id: 136,
       name: 'FLAREON',
       type1: 'FIRE',
       type2: '',
       baseAttack: 246,
       baseDefense: 204,
       baseHP: 130,
       possibleFM: [ 'FIRE SPIN', 'EMBER' ],
       possibleCM: [ 'OVERHEAT', 'FLAMETHROWER', 'FIRE BLAST' ] },
     { id: 137,
       name: 'PORYGON',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 153,
       baseDefense: 139,
       baseHP: 130,
       possibleFM: [ 'HIDDEN POWER', 'CHARGE BEAM' ],
       possibleCM: [ 'ZAP CANNON', 'HYPER BEAM', 'SOLAR BEAM' ] },
     { id: 138,
       name: 'OMANYTE',
       type1: 'ROCK',
       type2: 'WATER',
       baseAttack: 155,
       baseDefense: 174,
       baseHP: 70,
       possibleFM: [ 'MUD SHOT', 'WATER GUN' ],
       possibleCM: [ 'ROCK BLAST', 'BUBBLE BEAM', 'ANCIENT POWER' ] },
     { id: 139,
       name: 'OMASTAR',
       type1: 'ROCK',
       type2: 'WATER',
       baseAttack: 207,
       baseDefense: 227,
       baseHP: 140,
       possibleFM: [ 'WATER GUN', 'MUD SHOT' ],
       possibleCM: [ 'ROCK BLAST', 'HYDRO PUMP', 'ANCIENT POWER' ] },
     { id: 140,
       name: 'KABUTO',
       type1: 'ROCK',
       type2: 'WATER',
       baseAttack: 148,
       baseDefense: 162,
       baseHP: 60,
       possibleFM: [ 'MUD SHOT', 'SCRATCH' ],
       possibleCM: [ 'ROCK TOMB', 'AQUA JET', 'ANCIENT POWER' ] },
     { id: 141,
       name: 'KABUTOPS',
       type1: 'ROCK',
       type2: 'WATER',
       baseAttack: 220,
       baseDefense: 203,
       baseHP: 120,
       possibleFM: [ 'ROCK SMASH', 'MUD SHOT' ],
       possibleCM: [ 'STONE EDGE', 'WATER PULSE', 'ANCIENT POWER' ] },
     { id: 142,
       name: 'AERODACTYL',
       type1: 'ROCK',
       type2: 'FLYING',
       baseAttack: 221,
       baseDefense: 164,
       baseHP: 160,
       possibleFM: [ 'BITE', 'STEEL WING' ],
       possibleCM: [ 'HYPER BEAM', 'IRON HEAD', 'ANCIENT POWER' ] },
     { id: 143,
       name: 'SNORLAX',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 190,
       baseDefense: 190,
       baseHP: 320,
       possibleFM: [ 'LICK', 'ZEN HEADBUTT' ],
       possibleCM: [ 'EARTHQUAKE', 'HYPER BEAM', 'HEAVY SLAM' ] },
     { id: 144,
       name: 'ARTICUNO',
       type1: 'ICE',
       type2: 'FLYING',
       baseAttack: 192,
       baseDefense: 249,
       baseHP: 180,
       possibleFM: [ 'FROST BREATH' ],
       possibleCM: [ 'BLIZZARD', 'ICY WIND', 'ICE BEAM' ] },
     { id: 145,
       name: 'ZAPDOS',
       type1: 'ELECTRIC',
       type2: 'FLYING',
       baseAttack: 253,
       baseDefense: 188,
       baseHP: 180,
       possibleFM: [ 'CHARGE BEAM' ],
       possibleCM: [ 'THUNDER', 'THUNDERBOLT', 'ZAP CANNON' ] },
     { id: 146,
       name: 'MOLTRES',
       type1: 'FIRE',
       type2: 'FLYING',
       baseAttack: 251,
       baseDefense: 184,
       baseHP: 180,
       possibleFM: [ 'FIRE SPIN' ],
       possibleCM: [ 'OVERHEAT', 'HEAT WAVE', 'FIRE BLAST' ] },
     { id: 147,
       name: 'DRATINI',
       type1: 'DRAGON',
       type2: '',
       baseAttack: 119,
       baseDefense: 94,
       baseHP: 82,
       possibleFM: [ 'IRON TAIL', 'DRAGON BREATH' ],
       possibleCM: [ 'AQUA TAIL', 'TWISTER', 'WRAP' ] },
     { id: 148,
       name: 'DRAGONAIR',
       type1: 'DRAGON',
       type2: '',
       baseAttack: 163,
       baseDefense: 138,
       baseHP: 122,
       possibleFM: [ 'IRON TAIL', 'DRAGON BREATH' ],
       possibleCM: [ 'DRAGON PULSE', 'AQUA TAIL', 'WRAP' ] },
     { id: 149,
       name: 'DRAGONITE',
       type1: 'DRAGON',
       type2: 'FLYING',
       baseAttack: 263,
       baseDefense: 201,
       baseHP: 182,
       possibleFM: [ 'STEEL WING', 'DRAGON TAIL' ],
       possibleCM: [ 'OUTRAGE', 'HYPER BEAM', 'HURRICANE' ] },
     { id: 150,
       name: 'MEWTWO',
       type1: 'PSYCHIC',
       type2: '',
       baseAttack: 330,
       baseDefense: 200,
       baseHP: 212,
       possibleFM: [ 'CONFUSION', 'PSYCHO CUT' ],
       possibleCM: [ 'FOCUS BLAST', 'HYPER BEAM', 'SHADOW BALL', 'PSYCHIC' ] },
     { id: 151,
       name: 'MEW',
       type1: 'PSYCHIC',
       type2: '',
       baseAttack: 210,
       baseDefense: 210,
       baseHP: 200,
       possibleFM: [ 'POUND' ],
       possibleCM:
        [ 'HYPER BEAM',
          'SOLAR BEAM',
          'FIRE BLAST',
          'THUNDER',
          'FOCUS BLAST',
          'PSYCHIC',
          'EARTHQUAKE',
          'BLIZZARD' ] },
     { id: 152,
       name: 'CHIKORITA',
       type1: 'GRASS',
       type2: '',
       baseAttack: 92,
       baseDefense: 122,
       baseHP: 90,
       possibleFM: [ 'TACKLE', 'VINE WHIP' ],
       possibleCM: [ 'BODY SLAM', 'GRASS KNOT', 'ENERGY BALL' ] },
     { id: 153,
       name: 'BAYLEEF',
       type1: 'GRASS',
       type2: '',
       baseAttack: 122,
       baseDefense: 155,
       baseHP: 120,
       possibleFM: [ 'TACKLE', 'RAZOR LEAF' ],
       possibleCM: [ 'ANCIENT POWER', 'GRASS KNOT', 'ENERGY BALL' ] },
     { id: 154,
       name: 'MEGANIUM',
       type1: 'GRASS',
       type2: '',
       baseAttack: 168,
       baseDefense: 202,
       baseHP: 160,
       possibleFM: [ 'VINE WHIP', 'RAZOR LEAF' ],
       possibleCM: [ 'EARTHQUAKE', 'SOLAR BEAM', 'PETAL BLIZZARD' ] },
     { id: 155,
       name: 'CYNDAQUIL',
       type1: 'FIRE',
       type2: '',
       baseAttack: 116,
       baseDefense: 96,
       baseHP: 78,
       possibleFM: [ 'TACKLE', 'EMBER' ],
       possibleCM: [ 'FLAMETHROWER', 'SWIFT', 'FLAME CHARGE' ] },
     { id: 156,
       name: 'QUILAVA',
       type1: 'FIRE',
       type2: '',
       baseAttack: 158,
       baseDefense: 129,
       baseHP: 116,
       possibleFM: [ 'TACKLE', 'EMBER' ],
       possibleCM: [ 'FLAMETHROWER', 'DIG', 'FLAME CHARGE' ] },
     { id: 157,
       name: 'TYPHLOSION',
       type1: 'FIRE',
       type2: '',
       baseAttack: 223,
       baseDefense: 176,
       baseHP: 156,
       possibleFM: [ 'SHADOW CLAW', 'EMBER' ],
       possibleCM: [ 'SOLAR BEAM', 'OVERHEAT', 'FIRE BLAST' ] },
     { id: 158,
       name: 'TOTODILE',
       type1: 'WATER',
       type2: '',
       baseAttack: 117,
       baseDefense: 116,
       baseHP: 100,
       possibleFM: [ 'SCRATCH', 'WATER GUN' ],
       possibleCM: [ 'WATER PULSE', 'AQUA JET', 'CRUNCH' ] },
     { id: 159,
       name: 'CROCONAW',
       type1: 'WATER',
       type2: '',
       baseAttack: 150,
       baseDefense: 151,
       baseHP: 130,
       possibleFM: [ 'SCRATCH', 'WATER GUN' ],
       possibleCM: [ 'WATER PULSE', 'ICE PUNCH', 'CRUNCH' ] },
     { id: 160,
       name: 'FERALIGATR',
       type1: 'WATER',
       type2: '',
       baseAttack: 205,
       baseDefense: 197,
       baseHP: 170,
       possibleFM: [ 'BITE', 'WATER GUN' ],
       possibleCM: [ 'ICE BEAM', 'HYDRO PUMP', 'CRUNCH' ] },
     { id: 161,
       name: 'SENTRET',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 79,
       baseDefense: 77,
       baseHP: 70,
       possibleFM: [ 'QUICK ATTACK', 'SCRATCH' ],
       possibleCM: [ 'GRASS KNOT', 'BRICK BREAK', 'DIG' ] },
     { id: 162,
       name: 'FURRET',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 148,
       baseDefense: 130,
       baseHP: 170,
       possibleFM: [ 'SUCKER PUNCH', 'QUICK ATTACK' ],
       possibleCM: [ 'HYPER BEAM', 'BRICK BREAK', 'DIG' ] },
     { id: 163,
       name: 'HOOTHOOT',
       type1: 'NORMAL',
       type2: 'FLYING',
       baseAttack: 67,
       baseDefense: 101,
       baseHP: 120,
       possibleFM: [ 'PECK', 'FEINT ATTACK' ],
       possibleCM: [ 'BLIZZARD' ] },
     { id: 164,
       name: 'NOCTOWL',
       type1: 'NORMAL',
       type2: 'FLYING',
       baseAttack: 145,
       baseDefense: 179,
       baseHP: 200,
       possibleFM: [ 'EXTRASENSORY', 'WING ATTACK' ],
       possibleCM: [ 'NIGHT SHADE', 'SKY ATTACK', 'PSYCHIC' ] },
     { id: 165,
       name: 'LEDYBA',
       type1: 'BUG',
       type2: 'FLYING',
       baseAttack: 72,
       baseDefense: 142,
       baseHP: 80,
       possibleFM: [ 'BUG BITE', 'TACKLE' ],
       possibleCM: [ 'AERIAL ACE', 'SWIFT', 'SILVER WIND' ] },
     { id: 166,
       name: 'LEDIAN',
       type1: 'BUG',
       type2: 'FLYING',
       baseAttack: 107,
       baseDefense: 209,
       baseHP: 110,
       possibleFM: [ 'BUG BITE', 'STRUGGLE BUG' ],
       possibleCM: [ 'AERIAL ACE', 'SILVER WIND', 'BUG BUZZ' ] },
     { id: 167,
       name: 'SPINARAK',
       type1: 'BUG',
       type2: 'POISON',
       baseAttack: 105,
       baseDefense: 73,
       baseHP: 80,
       possibleFM: [ 'BUG BITE', 'POISON STING' ],
       possibleCM: [ 'CROSS POISON', 'SIGNAL BEAM', 'NIGHT SLASH' ] },
     { id: 168,
       name: 'ARIADOS',
       type1: 'BUG',
       type2: 'POISON',
       baseAttack: 161,
       baseDefense: 128,
       baseHP: 140,
       possibleFM: [ 'INFESTATION', 'POISON STING' ],
       possibleCM: [ 'CROSS POISON', 'MEGAHORN', 'SHADOW SNEAK' ] },
     { id: 169,
       name: 'CROBAT',
       type1: 'POISON',
       type2: 'FLYING',
       baseAttack: 194,
       baseDefense: 178,
       baseHP: 170,
       possibleFM: [ 'BITE', 'AIR SLASH' ],
       possibleCM: [ 'SLUDGE BOMB', 'AIR CUTTER', 'SHADOW BALL' ] },
     { id: 170,
       name: 'CHINCHOU',
       type1: 'WATER',
       type2: 'ELECTRIC',
       baseAttack: 106,
       baseDefense: 106,
       baseHP: 150,
       possibleFM: [ 'SPARK', 'BUBBLE' ],
       possibleCM: [ 'BUBBLE BEAM', 'THUNDERBOLT', 'WATER PULSE' ] },
     { id: 171,
       name: 'LANTURN',
       type1: 'WATER',
       type2: 'ELECTRIC',
       baseAttack: 146,
       baseDefense: 146,
       baseHP: 250,
       possibleFM: [ 'CHARGE BEAM', 'WATER GUN' ],
       possibleCM: [ 'THUNDER', 'THUNDERBOLT', 'HYDRO PUMP' ] },
     { id: 172,
       name: 'PICHU',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 77,
       baseDefense: 63,
       baseHP: 40,
       possibleFM: [ 'THUNDER SHOCK' ],
       possibleCM: [ 'THUNDER PUNCH', 'DISARMING VOICE', 'THUNDERBOLT' ] },
     { id: 173,
       name: 'CLEFFA',
       type1: 'FAIRY',
       type2: '',
       baseAttack: 75,
       baseDefense: 91,
       baseHP: 100,
       possibleFM: [ 'ZEN HEADBUTT', 'POUND' ],
       possibleCM: [ 'SIGNAL BEAM', 'PSYSHOCK', 'GRASS KNOT' ] },
     { id: 174,
       name: 'IGGLYBUFF',
       type1: 'NORMAL',
       type2: 'FAIRY',
       baseAttack: 69,
       baseDefense: 34,
       baseHP: 180,
       possibleFM: [ 'FEINT ATTACK', 'POUND' ],
       possibleCM: [ 'PSYCHIC', 'SHADOW BALL', 'WILD CHARGE' ] },
     { id: 175,
       name: 'TOGEPI',
       type1: 'FAIRY',
       type2: '',
       baseAttack: 67,
       baseDefense: 116,
       baseHP: 70,
       possibleFM: [ 'PECK', 'HIDDEN POWER' ],
       possibleCM: [ 'DAZZLING GLEAM', 'PSYSHOCK', 'ANCIENT POWER' ] },
     { id: 176,
       name: 'TOGETIC',
       type1: 'FAIRY',
       type2: 'FLYING',
       baseAttack: 139,
       baseDefense: 191,
       baseHP: 110,
       possibleFM: [ 'HIDDEN POWER', 'EXTRASENSORY' ],
       possibleCM: [ 'AERIAL ACE', 'DAZZLING GLEAM', 'ANCIENT POWER' ] },
     { id: 177,
       name: 'NATU',
       type1: 'PSYCHIC',
       type2: 'FLYING',
       baseAttack: 134,
       baseDefense: 89,
       baseHP: 80,
       possibleFM: [ 'QUICK ATTACK', 'PECK' ],
       possibleCM: [ 'DRILL PECK', 'PSYSHOCK', 'NIGHT SHADE' ] },
     { id: 178,
       name: 'XATU',
       type1: 'PSYCHIC',
       type2: 'FLYING',
       baseAttack: 192,
       baseDefense: 146,
       baseHP: 130,
       possibleFM: [ 'FEINT ATTACK', 'AIR SLASH' ],
       possibleCM: [ 'AERIAL ACE', 'FUTURESIGHT', 'OMINOUS WIND' ] },
     { id: 179,
       name: 'MAREEP',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 114,
       baseDefense: 82,
       baseHP: 110,
       possibleFM: [ 'THUNDER SHOCK', 'TACKLE' ],
       possibleCM: [ 'DISCHARGE', 'THUNDERBOLT', 'BODY SLAM' ] },
     { id: 180,
       name: 'FLAAFFY',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 145,
       baseDefense: 112,
       baseHP: 140,
       possibleFM: [ 'CHARGE BEAM', 'TACKLE' ],
       possibleCM: [ 'DISCHARGE', 'THUNDERBOLT', 'POWER GEM' ] },
     { id: 181,
       name: 'AMPHAROS',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 211,
       baseDefense: 172,
       baseHP: 180,
       possibleFM: [ 'VOLT SWITCH', 'CHARGE BEAM' ],
       possibleCM: [ 'THUNDER', 'FOCUS BLAST', 'ZAP CANNON' ] },
     { id: 182,
       name: 'BELLOSSOM',
       type1: 'GRASS',
       type2: '',
       baseAttack: 169,
       baseDefense: 189,
       baseHP: 150,
       possibleFM: [ 'ACID', 'RAZOR LEAF' ],
       possibleCM: [ 'DAZZLING GLEAM', 'PETAL BLIZZARD', 'LEAF BLADE' ] },
     { id: 183,
       name: 'MARILL',
       type1: 'WATER',
       type2: 'FAIRY',
       baseAttack: 37,
       baseDefense: 93,
       baseHP: 140,
       possibleFM: [ 'BUBBLE', 'TACKLE' ],
       possibleCM: [ 'BODY SLAM', 'AQUA TAIL', 'BUBBLE BEAM' ] },
     { id: 184,
       name: 'AZUMARILL',
       type1: 'WATER',
       type2: 'FAIRY',
       baseAttack: 112,
       baseDefense: 152,
       baseHP: 200,
       possibleFM: [ 'BUBBLE', 'ROCK SMASH' ],
       possibleCM: [ 'ICE BEAM', 'HYDRO PUMP', 'PLAY ROUGH' ] },
     { id: 185,
       name: 'SUDOWOODO',
       type1: 'ROCK',
       type2: '',
       baseAttack: 167,
       baseDefense: 198,
       baseHP: 140,
       possibleFM: [ 'COUNTER', 'ROCK THROW' ],
       possibleCM: [ 'ROCK SLIDE', 'EARTHQUAKE', 'STONE EDGE' ] },
     { id: 186,
       name: 'POLITOED',
       type1: 'WATER',
       type2: '',
       baseAttack: 174,
       baseDefense: 192,
       baseHP: 180,
       possibleFM: [ 'BUBBLE', 'MUD SHOT' ],
       possibleCM: [ 'EARTHQUAKE', 'BLIZZARD', 'HYDRO PUMP' ] },
     { id: 187,
       name: 'HOPPIP',
       type1: 'GRASS',
       type2: 'FLYING',
       baseAttack: 67,
       baseDefense: 101,
       baseHP: 70,
       possibleFM: [ 'BULLET SEED', 'TACKLE' ],
       possibleCM: [ 'SEED BOMB', 'DAZZLING GLEAM', 'GRASS KNOT' ] },
     { id: 188,
       name: 'SKIPLOOM',
       type1: 'GRASS',
       type2: 'FLYING',
       baseAttack: 91,
       baseDefense: 127,
       baseHP: 110,
       possibleFM: [ 'BULLET SEED', 'TACKLE' ],
       possibleCM: [ 'ENERGY BALL', 'DAZZLING GLEAM', 'GRASS KNOT' ] },
     { id: 189,
       name: 'JUMPLUFF',
       type1: 'GRASS',
       type2: 'FLYING',
       baseAttack: 118,
       baseDefense: 197,
       baseHP: 150,
       possibleFM: [ 'BULLET SEED', 'INFESTATION' ],
       possibleCM: [ 'SOLAR BEAM', 'DAZZLING GLEAM', 'ENERGY BALL' ] },
     { id: 190,
       name: 'AIPOM',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 136,
       baseDefense: 112,
       baseHP: 110,
       possibleFM: [ 'ASTONISH', 'SCRATCH' ],
       possibleCM: [ 'AERIAL ACE', 'SWIFT', 'LOW SWEEP' ] },
     { id: 191,
       name: 'SUNKERN',
       type1: 'GRASS',
       type2: '',
       baseAttack: 55,
       baseDefense: 55,
       baseHP: 60,
       possibleFM: [ 'CUT', 'RAZOR LEAF' ],
       possibleCM: [ 'SEED BOMB', 'GRASS KNOT', 'ENERGY BALL' ] },
     { id: 192,
       name: 'SUNFLORA',
       type1: 'GRASS',
       type2: '',
       baseAttack: 185,
       baseDefense: 148,
       baseHP: 150,
       possibleFM: [ 'BULLET SEED', 'RAZOR LEAF' ],
       possibleCM: [ 'SLUDGE BOMB', 'PETAL BLIZZARD', 'SOLAR BEAM' ] },
     { id: 193,
       name: 'YANMA',
       type1: 'BUG',
       type2: 'FLYING',
       baseAttack: 154,
       baseDefense: 94,
       baseHP: 130,
       possibleFM: [ 'WING ATTACK', 'QUICK ATTACK' ],
       possibleCM: [ 'SILVER WIND', 'AERIAL ACE', 'ANCIENT POWER' ] },
     { id: 194,
       name: 'WOOPER',
       type1: 'WATER',
       type2: 'GROUND',
       baseAttack: 75,
       baseDefense: 75,
       baseHP: 110,
       possibleFM: [ 'MUD SHOT', 'WATER GUN' ],
       possibleCM: [ 'BODY SLAM', 'DIG', 'MUD BOMB' ] },
     { id: 195,
       name: 'QUAGSIRE',
       type1: 'WATER',
       type2: 'GROUND',
       baseAttack: 152,
       baseDefense: 152,
       baseHP: 190,
       possibleFM: [ 'MUD SHOT', 'WATER GUN' ],
       possibleCM: [ 'STONE EDGE', 'EARTHQUAKE', 'SLUDGE BOMB' ] },
     { id: 196,
       name: 'ESPEON',
       type1: 'PSYCHIC',
       type2: '',
       baseAttack: 261,
       baseDefense: 194,
       baseHP: 130,
       possibleFM: [ 'ZEN HEADBUTT', 'CONFUSION' ],
       possibleCM: [ 'FUTURESIGHT', 'PSYCHIC', 'PSYBEAM' ] },
     { id: 197,
       name: 'UMBREON',
       type1: 'DARK',
       type2: '',
       baseAttack: 126,
       baseDefense: 250,
       baseHP: 190,
       possibleFM: [ 'SNARL', 'FEINT ATTACK' ],
       possibleCM: [ 'FOUL PLAY', 'DARK PULSE' ] },
     { id: 198,
       name: 'MURKROW',
       type1: 'DARK',
       type2: 'FLYING',
       baseAttack: 175,
       baseDefense: 87,
       baseHP: 120,
       possibleFM: [ 'FEINT ATTACK', 'PECK' ],
       possibleCM: [ 'DARK PULSE', 'FOUL PLAY', 'DRILL PECK' ] },
     { id: 199,
       name: 'SLOWKING',
       type1: 'WATER',
       type2: 'PSYCHIC',
       baseAttack: 177,
       baseDefense: 194,
       baseHP: 190,
       possibleFM: [ 'CONFUSION', 'WATER GUN' ],
       possibleCM: [ 'FIRE BLAST', 'PSYCHIC', 'BLIZZARD' ] },
     { id: 200,
       name: 'MISDREAVUS',
       type1: 'GHOST',
       type2: '',
       baseAttack: 167,
       baseDefense: 167,
       baseHP: 120,
       possibleFM: [ 'HEX', 'ASTONISH' ],
       possibleCM: [ 'OMINOUS WIND', 'DARK PULSE', 'SHADOW SNEAK' ] },
     { id: 201,
       name: 'UNOWN',
       type1: 'PSYCHIC',
       type2: '',
       baseAttack: 136,
       baseDefense: 91,
       baseHP: 96,
       possibleFM: [ 'HIDDEN POWER' ],
       possibleCM: [ 'STRUGGLE' ] },
     { id: 202,
       name: 'WOBBUFFET',
       type1: 'PSYCHIC',
       type2: '',
       baseAttack: 60,
       baseDefense: 106,
       baseHP: 380,
       possibleFM: [ 'SPLASH', 'COUNTER' ],
       possibleCM: [ 'MIRROR COAT' ] },
     { id: 203,
       name: 'GIRAFARIG',
       type1: 'NORMAL',
       type2: 'PSYCHIC',
       baseAttack: 182,
       baseDefense: 133,
       baseHP: 140,
       possibleFM: [ 'CONFUSION', 'TACKLE' ],
       possibleCM: [ 'MIRROR COAT', 'THUNDERBOLT', 'PSYCHIC' ] },
     { id: 204,
       name: 'PINECO',
       type1: 'BUG',
       type2: '',
       baseAttack: 108,
       baseDefense: 146,
       baseHP: 100,
       possibleFM: [ 'BUG BITE', 'TACKLE' ],
       possibleCM: [ 'SAND TOMB', 'ROCK TOMB', 'GYRO BALL' ] },
     { id: 205,
       name: 'FORRETRESS',
       type1: 'BUG',
       type2: 'STEEL',
       baseAttack: 161,
       baseDefense: 242,
       baseHP: 150,
       possibleFM: [ 'STRUGGLE BUG', 'BUG BITE' ],
       possibleCM: [ 'ROCK TOMB', 'EARTHQUAKE', 'HEAVY SLAM' ] },
     { id: 206,
       name: 'DUNSPARCE',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 131,
       baseDefense: 131,
       baseHP: 200,
       possibleFM: [ 'ASTONISH', 'BITE' ],
       possibleCM: [ 'DRILL RUN', 'ROCK SLIDE', 'DIG' ] },
     { id: 207,
       name: 'GLIGAR',
       type1: 'GROUND',
       type2: 'FLYING',
       baseAttack: 143,
       baseDefense: 204,
       baseHP: 130,
       possibleFM: [ 'WING ATTACK', 'FURY CUTTER' ],
       possibleCM: [ 'NIGHT SLASH', 'AERIAL ACE', 'DIG' ] },
     { id: 208,
       name: 'STEELIX',
       type1: 'STEEL',
       type2: 'GROUND',
       baseAttack: 148,
       baseDefense: 333,
       baseHP: 150,
       possibleFM: [ 'DRAGON TAIL', 'IRON TAIL' ],
       possibleCM: [ 'CRUNCH', 'HEAVY SLAM', 'EARTHQUAKE' ] },
     { id: 209,
       name: 'SNUBBULL',
       type1: 'FAIRY',
       type2: '',
       baseAttack: 137,
       baseDefense: 89,
       baseHP: 120,
       possibleFM: [ 'BITE', 'TACKLE' ],
       possibleCM: [ 'BRICK BREAK', 'DAZZLING GLEAM', 'CRUNCH' ] },
     { id: 210,
       name: 'GRANBULL',
       type1: 'FAIRY',
       type2: '',
       baseAttack: 212,
       baseDefense: 137,
       baseHP: 180,
       possibleFM: [ 'SNARL', 'BITE' ],
       possibleCM: [ 'CLOSE COMBAT', 'PLAY ROUGH', 'CRUNCH' ] },
     { id: 211,
       name: 'QWILFISH',
       type1: 'WATER',
       type2: 'POISON',
       baseAttack: 184,
       baseDefense: 148,
       baseHP: 130,
       possibleFM: [ 'WATER GUN', 'POISON STING' ],
       possibleCM: [ 'SLUDGE WAVE', 'ICE BEAM', 'AQUA TAIL' ] },
     { id: 212,
       name: 'SCIZOR',
       type1: 'BUG',
       type2: 'STEEL',
       baseAttack: 236,
       baseDefense: 191,
       baseHP: 140,
       possibleFM: [ 'FURY CUTTER', 'BULLET PUNCH' ],
       possibleCM: [ 'NIGHT SLASH', 'IRON HEAD', 'X SCISSOR' ] },
     { id: 213,
       name: 'SHUCKLE',
       type1: 'BUG',
       type2: 'ROCK',
       baseAttack: 17,
       baseDefense: 396,
       baseHP: 40,
       possibleFM: [ 'ROCK THROW', 'STRUGGLE BUG' ],
       possibleCM: [ 'GYRO BALL', 'STONE EDGE', 'ROCK BLAST' ] },
     { id: 214,
       name: 'HERACROSS',
       type1: 'BUG',
       type2: 'FIGHTING',
       baseAttack: 234,
       baseDefense: 189,
       baseHP: 160,
       possibleFM: [ 'STRUGGLE BUG', 'COUNTER' ],
       possibleCM: [ 'EARTHQUAKE', 'CLOSE COMBAT', 'MEGAHORN' ] },
     { id: 215,
       name: 'SNEASEL',
       type1: 'DARK',
       type2: 'ICE',
       baseAttack: 189,
       baseDefense: 157,
       baseHP: 110,
       possibleFM: [ 'FEINT ATTACK', 'ICE SHARD' ],
       possibleCM: [ 'FOUL PLAY', 'ICE PUNCH', 'AVALANCHE' ] },
     { id: 216,
       name: 'TEDDIURSA',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 142,
       baseDefense: 93,
       baseHP: 120,
       possibleFM: [ 'LICK', 'SCRATCH' ],
       possibleCM: [ 'PLAY ROUGH', 'CRUNCH', 'CROSS CHOP' ] },
     { id: 217,
       name: 'URSARING',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 236,
       baseDefense: 144,
       baseHP: 180,
       possibleFM: [ 'COUNTER', 'METAL CLAW' ],
       possibleCM: [ 'PLAY ROUGH', 'HYPER BEAM', 'CLOSE COMBAT' ] },
     { id: 218,
       name: 'SLUGMA',
       type1: 'FIRE',
       type2: '',
       baseAttack: 118,
       baseDefense: 71,
       baseHP: 80,
       possibleFM: [ 'ROCK THROW', 'EMBER' ],
       possibleCM: [ 'ROCK SLIDE', 'FLAME CHARGE', 'FLAME BURST' ] },
     { id: 219,
       name: 'MAGCARGO',
       type1: 'FIRE',
       type2: 'ROCK',
       baseAttack: 139,
       baseDefense: 209,
       baseHP: 100,
       possibleFM: [ 'ROCK THROW', 'EMBER' ],
       possibleCM: [ 'STONE EDGE', 'OVERHEAT', 'HEAT WAVE' ] },
     { id: 220,
       name: 'SWINUB',
       type1: 'ICE',
       type2: 'GROUND',
       baseAttack: 90,
       baseDefense: 74,
       baseHP: 100,
       possibleFM: [ 'POWDER SNOW', 'TACKLE' ],
       possibleCM: [ 'ROCK SLIDE', 'BODY SLAM', 'ICY WIND' ] },
     { id: 221,
       name: 'PILOSWINE',
       type1: 'ICE',
       type2: 'GROUND',
       baseAttack: 181,
       baseDefense: 147,
       baseHP: 200,
       possibleFM: [ 'POWDER SNOW', 'ICE SHARD' ],
       possibleCM: [ 'STONE EDGE', 'BULLDOZE', 'AVALANCHE' ] },
     { id: 222,
       name: 'CORSOLA',
       type1: 'WATER',
       type2: 'ROCK',
       baseAttack: 118,
       baseDefense: 156,
       baseHP: 110,
       possibleFM: [ 'BUBBLE', 'TACKLE' ],
       possibleCM: [ 'BUBBLE BEAM', 'POWER GEM', 'ROCK BLAST' ] },
     { id: 223,
       name: 'REMORAID',
       type1: 'WATER',
       type2: '',
       baseAttack: 127,
       baseDefense: 69,
       baseHP: 70,
       possibleFM: [ 'MUD SHOT', 'WATER GUN' ],
       possibleCM: [ 'ROCK BLAST', 'WATER PULSE', 'AURORA BEAM' ] },
     { id: 224,
       name: 'OCTILLERY',
       type1: 'WATER',
       type2: '',
       baseAttack: 197,
       baseDefense: 141,
       baseHP: 150,
       possibleFM: [ 'MUD SHOT', 'WATER GUN' ],
       possibleCM: [ 'AURORA BEAM', 'WATER PULSE', 'GUNK SHOT' ] },
     { id: 225,
       name: 'DELIBIRD',
       type1: 'ICE',
       type2: 'FLYING',
       baseAttack: 128,
       baseDefense: 90,
       baseHP: 90,
       possibleFM: [ 'QUICK ATTACK', 'ICE SHARD' ],
       possibleCM: [ 'AERIAL ACE', 'ICY WIND', 'ICE PUNCH' ] },
     { id: 226,
       name: 'MANTINE',
       type1: 'WATER',
       type2: 'FLYING',
       baseAttack: 148,
       baseDefense: 260,
       baseHP: 130,
       possibleFM: [ 'WING ATTACK', 'BUBBLE' ],
       possibleCM: [ 'AERIAL ACE', 'ICE BEAM', 'WATER PULSE' ] },
     { id: 227,
       name: 'SKARMORY',
       type1: 'STEEL',
       type2: 'FLYING',
       baseAttack: 148,
       baseDefense: 260,
       baseHP: 130,
       possibleFM: [ 'AIR SLASH', 'STEEL WING' ],
       possibleCM: [ 'FLASH CANNON', 'SKY ATTACK', 'BRAVE BIRD' ] },
     { id: 228,
       name: 'HOUNDOUR',
       type1: 'DARK',
       type2: 'FIRE',
       baseAttack: 152,
       baseDefense: 93,
       baseHP: 90,
       possibleFM: [ 'EMBER', 'FEINT ATTACK' ],
       possibleCM: [ 'DARK PULSE', 'FLAMETHROWER', 'CRUNCH' ] },
     { id: 229,
       name: 'HOUNDOOM',
       type1: 'DARK',
       type2: 'FIRE',
       baseAttack: 224,
       baseDefense: 159,
       baseHP: 150,
       possibleFM: [ 'FIRE FANG', 'SNARL' ],
       possibleCM: [ 'FOUL PLAY', 'FIRE BLAST', 'CRUNCH' ] },
     { id: 230,
       name: 'KINGDRA',
       type1: 'WATER',
       type2: 'DRAGON',
       baseAttack: 194,
       baseDefense: 194,
       baseHP: 150,
       possibleFM: [ 'DRAGON BREATH', 'WATER GUN' ],
       possibleCM: [ 'OUTRAGE', 'BLIZZARD', 'HYDRO PUMP' ] },
     { id: 231,
       name: 'PHANPY',
       type1: 'GROUND',
       type2: '',
       baseAttack: 107,
       baseDefense: 107,
       baseHP: 180,
       possibleFM: [ 'ROCK SMASH', 'TACKLE' ],
       possibleCM: [ 'BODY SLAM', 'ROCK SLIDE', 'BULLDOZE' ] },
     { id: 232,
       name: 'DONPHAN',
       type1: 'GROUND',
       type2: '',
       baseAttack: 214,
       baseDefense: 214,
       baseHP: 180,
       possibleFM: [ 'COUNTER', 'TACKLE' ],
       possibleCM: [ 'PLAY ROUGH', 'HEAVY SLAM', 'EARTHQUAKE' ] },
     { id: 233,
       name: 'PORYGON2',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 198,
       baseDefense: 183,
       baseHP: 170,
       possibleFM: [ 'CHARGE BEAM', 'HIDDEN POWER' ],
       possibleCM: [ 'ZAP CANNON', 'HYPER BEAM', 'SOLAR BEAM' ] },
     { id: 234,
       name: 'STANTLER',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 192,
       baseDefense: 132,
       baseHP: 146,
       possibleFM: [ 'ZEN HEADBUTT', 'TACKLE' ],
       possibleCM: [ 'MEGAHORN', 'WILD CHARGE', 'STOMP' ] },
     { id: 235,
       name: 'SMEARGLE',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 40,
       baseDefense: 88,
       baseHP: 110,
       possibleFM: [ 'TACKLE' ],
       possibleCM: [ 'STRUGGLE' ] },
     { id: 236,
       name: 'TYROGUE',
       type1: 'FIGHTING',
       type2: '',
       baseAttack: 64,
       baseDefense: 64,
       baseHP: 70,
       possibleFM: [ 'TACKLE', 'ROCK SMASH' ],
       possibleCM: [ 'LOW SWEEP', 'ROCK SLIDE', 'BRICK BREAK' ] },
     { id: 237,
       name: 'HITMONTOP',
       type1: 'FIGHTING',
       type2: '',
       baseAttack: 173,
       baseDefense: 214,
       baseHP: 100,
       possibleFM: [ 'COUNTER', 'ROCK SMASH' ],
       possibleCM: [ 'STONE EDGE', 'GYRO BALL', 'CLOSE COMBAT' ] },
     { id: 238,
       name: 'SMOOCHUM',
       type1: 'ICE',
       type2: 'PSYCHIC',
       baseAttack: 153,
       baseDefense: 116,
       baseHP: 90,
       possibleFM: [ 'POUND', 'POWDER SNOW' ],
       possibleCM: [ 'PSYSHOCK', 'ICE PUNCH', 'ICE BEAM' ] },
     { id: 239,
       name: 'ELEKID',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 135,
       baseDefense: 110,
       baseHP: 90,
       possibleFM: [ 'LOW KICK', 'THUNDER SHOCK' ],
       possibleCM: [ 'DISCHARGE', 'BRICK BREAK', 'THUNDER PUNCH' ] },
     { id: 240,
       name: 'MAGBY',
       type1: 'FIRE',
       type2: '',
       baseAttack: 151,
       baseDefense: 108,
       baseHP: 90,
       possibleFM: [ 'KARATE CHOP', 'EMBER' ],
       possibleCM: [ 'FLAME BURST', 'FIRE PUNCH', 'BRICK BREAK' ] },
     { id: 241,
       name: 'MILTANK',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 157,
       baseDefense: 211,
       baseHP: 190,
       possibleFM: [ 'ZEN HEADBUTT', 'TACKLE' ],
       possibleCM: [ 'GYRO BALL', 'BODY SLAM', 'STOMP' ] },
     { id: 242,
       name: 'BLISSEY',
       type1: 'NORMAL',
       type2: '',
       baseAttack: 129,
       baseDefense: 229,
       baseHP: 510,
       possibleFM: [ 'ZEN HEADBUTT', 'POUND' ],
       possibleCM: [ 'DAZZLING GLEAM', 'HYPER BEAM', 'PSYCHIC' ] },
     { id: 243,
       name: 'RAIKOU',
       type1: 'ELECTRIC',
       type2: '',
       baseAttack: 241,
       baseDefense: 210,
       baseHP: 180,
       possibleFM: [ 'VOLT SWITCH', 'THUNDER SHOCK' ],
       possibleCM: [ 'WILD CHARGE', 'THUNDERBOLT', 'THUNDER' ] },
     { id: 244,
       name: 'ENTEI',
       type1: 'FIRE',
       type2: '',
       baseAttack: 235,
       baseDefense: 176,
       baseHP: 230,
       possibleFM: [ 'FIRE FANG', 'FIRE SPIN' ],
       possibleCM: [ 'OVERHEAT', 'FIRE BLAST', 'FLAMETHROWER' ] },
     { id: 245,
       name: 'SUICUNE',
       type1: 'WATER',
       type2: '',
       baseAttack: 180,
       baseDefense: 235,
       baseHP: 200,
       possibleFM: [ 'SNARL', 'EXTRASENSORY' ],
       possibleCM: [ 'WATER PULSE', 'BUBBLE BEAM', 'HYDRO PUMP' ] },
     { id: 246,
       name: 'LARVITAR',
       type1: 'ROCK',
       type2: 'GROUND',
       baseAttack: 115,
       baseDefense: 93,
       baseHP: 100,
       possibleFM: [ 'ROCK SMASH', 'BITE' ],
       possibleCM: [ 'ANCIENT POWER', 'CRUNCH', 'STOMP' ] },
     { id: 247,
       name: 'PUPITAR',
       type1: 'ROCK',
       type2: 'GROUND',
       baseAttack: 155,
       baseDefense: 133,
       baseHP: 140,
       possibleFM: [ 'ROCK SMASH', 'BITE' ],
       possibleCM: [ 'ANCIENT POWER', 'CRUNCH', 'DIG' ] },
     { id: 248,
       name: 'TYRANITAR',
       type1: 'ROCK',
       type2: 'DARK',
       baseAttack: 251,
       baseDefense: 212,
       baseHP: 200,
       possibleFM: [ 'IRON TAIL', 'BITE' ],
       possibleCM: [ 'STONE EDGE', 'CRUNCH', 'FIRE BLAST' ] },
     { id: 249,
       name: 'LUGIA',
       type1: 'PSYCHIC',
       type2: 'FLYING',
       baseAttack: 193,
       baseDefense: 323,
       baseHP: 212,
       possibleFM: [ 'DRAGON TAIL', 'EXTRASENSORY' ],
       possibleCM: [ 'FUTURESIGHT', 'HYDRO PUMP', 'SKY ATTACK' ] },
     { id: 250,
       name: 'HO_OH',
       type1: 'FIRE',
       type2: 'FLYING',
       baseAttack: 263,
       baseDefense: 301,
       baseHP: 212,
       possibleFM: [ 'STEEL WING', 'EXTRASENSORY' ],
       possibleCM: [ 'SOLAR BEAM', 'FIRE BLAST', 'BRAVE BIRD' ] },
     { id: 251,
       name: 'CELEBI',
       type1: 'PSYCHIC',
       type2: 'GRASS',
       baseAttack: 210,
       baseDefense: 210,
       baseHP: 200,
       possibleFM: [ 'CHARGE BEAM', 'CONFUSION' ],
       possibleCM: [ 'DAZZLING GLEAM', 'PSYCHIC', 'HYPER BEAM' ] } ],
  getPokemonReference: function(name){
   	var name = name.toUpperCase();
   	var found = false;
   	var pokemonReference;
   	this.pokemonReferenceArray.forEach(function(reference){
   		if (reference.name === name) {
   			pokemonReference = reference;
   			found = true;
   		}
   	});
    if (found){
      return pokemonReference;
      console.log(this.pokemonReference.name);
    }
    return false;
  },
  setAttacker(poke){
    poke.cpm = Math.sqrt(poke.level) * 0.1336;
  	poke.adjustedAttack = (poke.attackIV + poke.baseAttack) * poke.cpm;
  	poke.adjustedDefense = (poke.defenseIV + poke.baseDefense) * poke.cpm;
  	poke.adjustedHP = (poke.hpIV + poke.baseHP) * poke.cpm;
  	poke.cp = ((poke.baseAttack + poke.attackIV) * Math.sqrt(poke.baseDefense + poke.defenseIV) * Math.sqrt(poke.baseHP + poke.hpIV) * Math.pow(poke.cpm, 2)) / 10;
  },
  setDefender(poke){
    poke.attackIV = 15;
	  poke.defenseIV = 15;
	  poke.hpIV = 15;
    poke.cpm = Math.sqrt((poke.cp * 10) / ((poke.baseAttack + poke.attackIV) * Math.sqrt(poke.baseDefense + poke.defenseIV) * Math.sqrt(poke.baseHP + poke.hpIV)));
    poke.adjustedDefense = poke.cpm * (poke.baseDefense + 15);
    poke.adjustedAttack = poke.cpm * (poke.baseAttack + 15);
    poke.adjustedStamina = poke.cpm * (poke.baseHP + 15);
    poke.level = Math.pow((poke.cpm / 0.1336), 2);
  }
}



module.exports = ReferencePokemon;
