var React = require('react');
var ReactDOM = require('react-dom');

var ReferenceMoves = {};

ReferenceMoves.list = [{ dps: '13.75',
    name: 'STEEL WING',
    type: 'STEEL',
    energy: '+6',
    power: '11',
    duration: '800',
    enegyGPS: '7.5' },
  { dps: '13.64',
    name: 'IRON TAIL',
    type: 'STEEL',
    energy: '+7',
    power: '15',
    duration: '1,100',
    enegyGPS: '6.36' },
  { dps: '13.64',
    name: 'DRAGON TAIL',
    type: 'DRAGON',
    energy: '+9',
    power: '15',
    duration: '1,100',
    enegyGPS: '8.18' },
  { dps: '13.33',
    name: 'ROCK THROW',
    type: 'ROCK',
    energy: '+7',
    power: '12',
    duration: '900',
    enegyGPS: '7.78' },
  { dps: '13.33',
    name: 'COUNTER',
    type: 'FIGHTING',
    energy: '+8',
    power: '12',
    duration: '900',
    enegyGPS: '8.89' },
  { dps: '13',
    name: 'RAZOR LEAF',
    type: 'GRASS',
    energy: '+7',
    power: '13',
    duration: '1,000',
    enegyGPS: '7' },
  { dps: '12.86',
    name: 'SHADOW CLAW',
    type: 'GHOST',
    energy: '+6',
    power: '9',
    duration: '700',
    enegyGPS: '8.57' },
  { dps: '12.73',
    name: 'FIRE SPIN',
    type: 'FIRE',
    energy: '+10',
    power: '14',
    duration: '1,100',
    enegyGPS: '9.09' },
  { dps: '12.5',
    name: 'CONFUSION',
    type: 'PSYCHIC',
    energy: '+15',
    power: '20',
    duration: '1,600',
    enegyGPS: '9.38' },
  { dps: '12.5',
    name: 'POISON JAB',
    type: 'POISON',
    energy: '+7',
    power: '10',
    duration: '800',
    enegyGPS: '8.75' },
  { dps: '12.22',
    name: 'FIRE FANG',
    type: 'FIRE',
    energy: '+8',
    power: '11',
    duration: '900',
    enegyGPS: '8.89' },
  { dps: '12',
    name: 'DRAGON BREATH',
    type: 'DRAGON',
    energy: '+4',
    power: '6',
    duration: '500',
    enegyGPS: '8' },
  { dps: '12',
    name: 'SCRATCH',
    type: 'NORMAL',
    energy: '+4',
    power: '6',
    duration: '500',
    enegyGPS: '8' },
  { dps: '12',
    name: 'BITE',
    type: 'DARK',
    energy: '+4',
    power: '6',
    duration: '500',
    enegyGPS: '8' },
  { dps: '11.67',
    name: 'VINE WHIP',
    type: 'GRASS',
    energy: '+6',
    power: '7',
    duration: '600',
    enegyGPS: '10' },
  { dps: '11.67',
    name: 'POUND',
    type: 'NORMAL',
    energy: '+6',
    power: '7',
    duration: '600',
    enegyGPS: '10' },
  { dps: '11.67',
    name: 'AIR SLASH',
    type: 'FLYING',
    energy: '+10',
    power: '14',
    duration: '1,200',
    enegyGPS: '8.33' },
  { dps: '11.54',
    name: 'ROCK SMASH',
    type: 'FIGHTING',
    energy: '+10',
    power: '15',
    duration: '1,300',
    enegyGPS: '7.69' },
  { dps: '11.43',
    name: 'METAL CLAW',
    type: 'STEEL',
    energy: '+7',
    power: '8',
    duration: '700',
    enegyGPS: '10' },
  { dps: '11.25',
    name: 'ACID',
    type: 'POISON',
    energy: '+8',
    power: '9',
    duration: '800',
    enegyGPS: '10' },
  { dps: '11.11',
    name: 'FROST BREATH',
    type: 'ICE',
    energy: '+8',
    power: '10',
    duration: '900',
    enegyGPS: '8.89' },
  { dps: '11.11',
    name: 'FEINT ATTACK',
    type: 'DARK',
    energy: '+9',
    power: '10',
    duration: '900',
    enegyGPS: '10' },
  { dps: '10.91',
    name: 'EXTRASENSORY',
    type: 'PSYCHIC',
    energy: '+12',
    power: '12',
    duration: '1,100',
    enegyGPS: '10.91' },
  { dps: '10.91',
    name: 'ZEN HEADBUTT',
    type: 'PSYCHIC',
    energy: '+10',
    power: '12',
    duration: '1,100',
    enegyGPS: '9.09' },
  { dps: '10.91',
    name: 'SNARL',
    type: 'DARK',
    energy: '+12',
    power: '12',
    duration: '1,100',
    enegyGPS: '10.91' },
  { dps: '10.71',
    name: 'MUD SLAP',
    type: 'GROUND',
    energy: '+12',
    power: '15',
    duration: '1,400',
    enegyGPS: '8.57' },
  { dps: '10',
    name: 'ICE SHARD',
    type: 'ICE',
    energy: '+12',
    power: '12',
    duration: '1,200',
    enegyGPS: '10' },
  { dps: '10',
    name: 'KARATE CHOP',
    type: 'FIGHTING',
    energy: '+10',
    power: '8',
    duration: '800',
    enegyGPS: '12.5' },
  { dps: '10',
    name: 'LOW KICK',
    type: 'FIGHTING',
    energy: '+6',
    power: '6',
    duration: '600',
    enegyGPS: '10' },
  { dps: '10',
    name: 'BULLET PUNCH',
    type: 'STEEL',
    energy: '+10',
    power: '9',
    duration: '900',
    enegyGPS: '11.11' },
  { dps: '10',
    name: 'BUBBLE',
    type: 'WATER',
    energy: '+14',
    power: '12',
    duration: '1,200',
    enegyGPS: '11.67' },
  { dps: '10',
    name: 'HIDDEN POWER',
    type: 'NORMAL',
    energy: '+15',
    power: '15',
    duration: '1,500',
    enegyGPS: '10' },
  { dps: '10',
    name: 'WATER GUN BLASTOISE',
    type: 'WATER',
    energy: '+6',
    power: '10',
    duration: '1,000',
    enegyGPS: '6' },
  { dps: '10',
    name: 'CUT',
    type: 'NORMAL',
    energy: '+5',
    power: '5',
    duration: '500',
    enegyGPS: '10' },
  { dps: '10',
    name: 'WATER GUN',
    type: 'WATER',
    energy: '+5',
    power: '5',
    duration: '500',
    enegyGPS: '10' },
  { dps: '10',
    name: 'TACKLE',
    type: 'NORMAL',
    energy: '+5',
    power: '5',
    duration: '500',
    enegyGPS: '10' },
  { dps: '10',
    name: 'LICK',
    type: 'GHOST',
    energy: '+6',
    power: '5',
    duration: '500',
    enegyGPS: '12' },
  { dps: '10',
    name: 'QUICK ATTACK',
    type: 'NORMAL',
    energy: '+10',
    power: '8',
    duration: '800',
    enegyGPS: '12.5' },
  { dps: '10',
    name: 'SUCKER PUNCH',
    type: 'DARK',
    energy: '+8',
    power: '7',
    duration: '700',
    enegyGPS: '11.43' },
  { dps: '10',
    name: 'STRUGGLE BUG',
    type: 'BUG',
    energy: '+15',
    power: '15',
    duration: '1,500',
    enegyGPS: '10' },
  { dps: '10',
    name: 'BUG BITE',
    type: 'BUG',
    energy: '+6',
    power: '5',
    duration: '500',
    enegyGPS: '12' },
  { dps: '10',
    name: 'PECK',
    type: 'FLYING',
    energy: '+10',
    power: '10',
    duration: '1,000',
    enegyGPS: '10' },
  { dps: '10',
    name: 'WING ATTACK',
    type: 'FLYING',
    energy: '+9',
    power: '8',
    duration: '800',
    enegyGPS: '11.25' },
  { dps: '10',
    name: 'EMBER',
    type: 'FIRE',
    energy: '+10',
    power: '10',
    duration: '1,000',
    enegyGPS: '10' },
  { dps: '9.09',
    name: 'INFESTATION',
    type: 'BUG',
    energy: '+14',
    power: '10',
    duration: '1,100',
    enegyGPS: '12.73' },
  { dps: '8.7',
    name: 'VOLT SWITCH',
    type: 'ELECTRIC',
    energy: '+25',
    power: '20',
    duration: '2,300',
    enegyGPS: '10.87' },
  { dps: '8.57',
    name: 'SPARK',
    type: 'ELECTRIC',
    energy: '+9',
    power: '6',
    duration: '700',
    enegyGPS: '12.86' },
  { dps: '8.33',
    name: 'MUD SHOT',
    type: 'GROUND',
    energy: '+7',
    power: '5',
    duration: '600',
    enegyGPS: '11.67' },
  { dps: '8.33',
    name: 'HEX',
    type: 'GHOST',
    energy: '+15',
    power: '10',
    duration: '1,200',
    enegyGPS: '12.5' },
  { dps: '8.33',
    name: 'PSYCHO CUT',
    type: 'PSYCHIC',
    energy: '+8',
    power: '5',
    duration: '600',
    enegyGPS: '13.33' },
  { dps: '8.33',
    name: 'POISON STING',
    type: 'POISON',
    energy: '+7',
    power: '5',
    duration: '600',
    enegyGPS: '11.67' },
  { dps: '8.33',
    name: 'THUNDER SHOCK',
    type: 'ELECTRIC',
    energy: '+8',
    power: '5',
    duration: '600',
    enegyGPS: '13.33' },
  { dps: '7.5',
    name: 'FURY CUTTER',
    type: 'BUG',
    energy: '+6',
    power: '3',
    duration: '400',
    enegyGPS: '15' },
  { dps: '7.27',
    name: 'BULLET SEED',
    type: 'GRASS',
    energy: '+14',
    power: '8',
    duration: '1,100',
    enegyGPS: '12.73' },
  { dps: '7.27',
    name: 'ASTONISH',
    type: 'GHOST',
    energy: '+14',
    power: '8',
    duration: '1,100',
    enegyGPS: '12.73' },
  { dps: '7.27',
    name: 'CHARGE BEAM',
    type: 'ELECTRIC',
    energy: '+15',
    power: '8',
    duration: '1,100',
    enegyGPS: '13.64' },
  { dps: '6',
    name: 'POWDER SNOW',
    type: 'ICE',
    energy: '+15',
    power: '6',
    duration: '1,000',
    enegyGPS: '15' },
  { dps: '0',
    name: 'TRANSFORM',
    type: 'NORMAL',
    energy: '+0',
    power: '0',
    duration: '2,230',
    enegyGPS: '0' },
  { dps: '0',
    name: 'SPLASH',
    type: 'WATER',
    energy: '+20',
    power: '0',
    duration: '1,730',
    enegyGPS: '11.56' },
  { dps: '45',
    name: 'BRAVE BIRD',
    type: 'FLYING',
    energy: '100',
    power: '90',
    duration: '2,000',
    fullBarDamage: '90' },
  { dps: '44.44',
    name: 'FUTURESIGHT',
    type: 'PSYCHIC',
    energy: '100',
    power: '120',
    duration: '2,700',
    fullBarDamage: '120' },
  { dps: '43.48',
    name: 'CLOSE COMBAT',
    type: 'FIGHTING',
    energy: '100',
    power: '100',
    duration: '2,300',
    fullBarDamage: '100' },
  { dps: '43.48',
    name: 'STONE EDGE',
    type: 'ROCK',
    energy: '100',
    power: '100',
    duration: '2,300',
    fullBarDamage: '100' },
  { dps: '42.31',
    name: 'PETAL BLIZZARD',
    type: 'GRASS',
    energy: '100',
    power: '110',
    duration: '2,600',
    fullBarDamage: '110' },
  { dps: '41.94',
    name: 'BLIZZARD',
    type: 'ICE',
    energy: '100',
    power: '130',
    duration: '3,100',
    fullBarDamage: '130' },
  { dps: '41.94',
    name: 'GUNK SHOT',
    type: 'POISON',
    energy: '100',
    power: '130',
    duration: '3,100',
    fullBarDamage: '130' },
  { dps: '41.67',
    name: 'THUNDER',
    type: 'ELECTRIC',
    energy: '100',
    power: '100',
    duration: '2,400',
    fullBarDamage: '100' },
  { dps: '40.91',
    name: 'MEGAHORN',
    type: 'BUG',
    energy: '100',
    power: '90',
    duration: '2,200',
    fullBarDamage: '90' },
  { dps: '40.74',
    name: 'HURRICANE',
    type: 'FLYING',
    energy: '100',
    power: '110',
    duration: '2,700',
    fullBarDamage: '110' },
  { dps: '40',
    name: 'FOCUS BLAST',
    type: 'FIGHTING',
    energy: '100',
    power: '140',
    duration: '3,500',
    fullBarDamage: '140' },
  { dps: '40',
    name: 'OVERHEAT',
    type: 'FIRE',
    energy: '100',
    power: '160',
    duration: '4,000',
    fullBarDamage: '160' },
  { dps: '39.47',
    name: 'HYPER BEAM',
    type: 'NORMAL',
    energy: '100',
    power: '150',
    duration: '3,800',
    fullBarDamage: '150' },
  { dps: '39.39',
    name: 'HYDRO PUMP',
    type: 'WATER',
    energy: '100',
    power: '130',
    duration: '3,300',
    fullBarDamage: '130' },
  { dps: '37.84',
    name: 'ZAP CANNON',
    type: 'ELECTRIC',
    energy: '100',
    power: '140',
    duration: '3,700',
    fullBarDamage: '140' },
  { dps: '37.04',
    name: 'FLASH CANNON',
    type: 'STEEL',
    energy: '100',
    power: '100',
    duration: '2,700',
    fullBarDamage: '100' },
  { dps: '36.73',
    name: 'SOLAR BEAM',
    type: 'GRASS',
    energy: '100',
    power: '180',
    duration: '4,900',
    fullBarDamage: '180' },
  { dps: '35.71',
    name: 'PSYCHIC',
    type: 'PSYCHIC',
    energy: '100',
    power: '100',
    duration: '2,800',
    fullBarDamage: '100' },
  { dps: '35',
    name: 'FOUL PLAY',
    type: 'DARK',
    energy: '50',
    power: '70',
    duration: '2,000',
    fullBarDamage: '140' },
  { dps: '35',
    name: 'SKY ATTACK',
    type: 'FLYING',
    energy: '50',
    power: '70',
    duration: '2,000',
    fullBarDamage: '140' },
  { dps: '34.78',
    name: 'SLUDGE BOMB',
    type: 'POISON',
    energy: '50',
    power: '80',
    duration: '2,300',
    fullBarDamage: '160' },
  { dps: '34.62',
    name: 'GRASS KNOT',
    type: 'GRASS',
    energy: '50',
    power: '90',
    duration: '2,600',
    fullBarDamage: '180' },
  { dps: '34.62',
    name: 'POWER WHIP',
    type: 'GRASS',
    energy: '50',
    power: '90',
    duration: '2,600',
    fullBarDamage: '180' },
  { dps: '34.62',
    name: 'WILD CHARGE',
    type: 'ELECTRIC',
    energy: '50',
    power: '90',
    duration: '2,600',
    fullBarDamage: '180' },
  { dps: '34.38',
    name: 'SLUDGE WAVE',
    type: 'POISON',
    energy: '100',
    power: '110',
    duration: '3,200',
    fullBarDamage: '110' },
  { dps: '33.33',
    name: 'FIRE BLAST',
    type: 'FIRE',
    energy: '100',
    power: '140',
    duration: '4,200',
    fullBarDamage: '140' },
  { dps: '33.33',
    name: 'AVALANCHE',
    type: 'ICE',
    energy: '50',
    power: '90',
    duration: '2,700',
    fullBarDamage: '180' },
  { dps: '33.33',
    name: 'DYNAMIC PUNCH',
    type: 'FIGHTING',
    energy: '50',
    power: '90',
    duration: '2,700',
    fullBarDamage: '180' },
  { dps: '33.33',
    name: 'HEAVY SLAM',
    type: 'STEEL',
    energy: '50',
    power: '70',
    duration: '2,100',
    fullBarDamage: '140' },
  { dps: '33.33',
    name: 'CROSS CHOP',
    type: 'FIGHTING',
    energy: '50',
    power: '50',
    duration: '1,500',
    fullBarDamage: '100' },
  { dps: '33.33',
    name: 'EARTHQUAKE',
    type: 'GROUND',
    energy: '100',
    power: '120',
    duration: '3,600',
    fullBarDamage: '120' },
  { dps: '33.33',
    name: 'MOONBLAST',
    type: 'FAIRY',
    energy: '100',
    power: '130',
    duration: '3,900',
    fullBarDamage: '130' },
  { dps: '33.33',
    name: 'SHADOW BALL',
    type: 'GHOST',
    energy: '50',
    power: '100',
    duration: '3,000',
    fullBarDamage: '200' },
  { dps: '32.35',
    name: 'STOMP',
    type: 'NORMAL',
    energy: '50',
    power: '55',
    duration: '1,700',
    fullBarDamage: '110' },
  { dps: '32',
    name: 'HYPER FANG',
    type: 'NORMAL',
    energy: '50',
    power: '80',
    duration: '2,500',
    fullBarDamage: '160' },
  { dps: '32',
    name: 'THUNDERBOLT',
    type: 'ELECTRIC',
    energy: '50',
    power: '80',
    duration: '2,500',
    fullBarDamage: '160' },
  { dps: '31.82',
    name: 'FLAMETHROWER',
    type: 'FIRE',
    energy: '50',
    power: '70',
    duration: '2,200',
    fullBarDamage: '140' },
  { dps: '31.67',
    name: 'HEAT WAVE',
    type: 'FIRE',
    energy: '100',
    power: '95',
    duration: '3,000',
    fullBarDamage: '95' },
  { dps: '31.58',
    name: 'IRON HEAD',
    type: 'STEEL',
    energy: '50',
    power: '60',
    duration: '1,900',
    fullBarDamage: '120' },
  { dps: '31.03',
    name: 'PLAY ROUGH',
    type: 'FAIRY',
    energy: '50',
    power: '90',
    duration: '2,900',
    fullBarDamage: '180' },
  { dps: '29.63',
    name: 'ROCK SLIDE',
    type: 'ROCK',
    energy: '50',
    power: '80',
    duration: '2,700',
    fullBarDamage: '160' },
  { dps: '29.41',
    name: 'DRAGON CLAW',
    type: 'DRAGON',
    energy: '33',
    power: '50',
    duration: '1,700',
    fullBarDamage: '150' },
  { dps: '29.17',
    name: 'LEAF BLADE',
    type: 'GRASS',
    energy: '33',
    power: '70',
    duration: '2,400',
    fullBarDamage: '210' },
  { dps: '28.57',
    name: 'DRILL RUN',
    type: 'GROUND',
    energy: '50',
    power: '80',
    duration: '2,800',
    fullBarDamage: '160' },
  { dps: '28.57',
    name: 'DAZZLING GLEAM',
    type: 'FAIRY',
    energy: '50',
    power: '100',
    duration: '3,500',
    fullBarDamage: '200' },
  { dps: '28.21',
    name: 'OUTRAGE',
    type: 'DRAGON',
    energy: '50',
    power: '110',
    duration: '3,900',
    fullBarDamage: '220' },
  { dps: '28.13',
    name: 'X SCISSOR',
    type: 'BUG',
    energy: '33',
    power: '45',
    duration: '1,600',
    fullBarDamage: '135' },
  { dps: '27.59',
    name: 'POWER GEM',
    type: 'ROCK',
    energy: '50',
    power: '80',
    duration: '2,900',
    fullBarDamage: '160' },
  { dps: '27.27',
    name: 'ICE BEAM',
    type: 'ICE',
    energy: '50',
    power: '90',
    duration: '3,300',
    fullBarDamage: '180' },
  { dps: '27.27',
    name: 'SUBMISSION',
    type: 'FIGHTING',
    energy: '50',
    power: '60',
    duration: '2,200',
    fullBarDamage: '120' },
  { dps: '26.92',
    name: 'FLAME BURST',
    type: 'FIRE',
    energy: '50',
    power: '70',
    duration: '2,600',
    fullBarDamage: '140' },
  { dps: '26.67',
    name: 'CROSS POISON',
    type: 'POISON',
    energy: '33',
    power: '40',
    duration: '1,500',
    fullBarDamage: '120' },
  { dps: '26.67',
    name: 'DARK PULSE',
    type: 'DARK',
    energy: '50',
    power: '80',
    duration: '3,000',
    fullBarDamage: '160' },
  { dps: '26.32',
    name: 'ICE PUNCH',
    type: 'ICE',
    energy: '33',
    power: '50',
    duration: '1,900',
    fullBarDamage: '150' },
  { dps: '26.32',
    name: 'AQUA TAIL',
    type: 'WATER',
    energy: '33',
    power: '50',
    duration: '1,900',
    fullBarDamage: '150' },
  { dps: '26.32',
    name: 'REST',
    type: 'NORMAL',
    energy: '33',
    power: '50',
    duration: '1,900',
    fullBarDamage: '150' },
  { dps: '26.32',
    name: 'BODY SLAM',
    type: 'NORMAL',
    energy: '33',
    power: '50',
    duration: '1,900',
    fullBarDamage: '150' },
  { dps: '26.19',
    name: 'SEED BOMB',
    type: 'GRASS',
    energy: '33',
    power: '55',
    duration: '2,100',
    fullBarDamage: '165' },
  { dps: '26.09',
    name: 'DRILL PECK',
    type: 'FLYING',
    energy: '33',
    power: '60',
    duration: '2,300',
    fullBarDamage: '180' },
  { dps: '26.09',
    name: 'BRINE',
    type: 'WATER',
    energy: '50',
    power: '60',
    duration: '2,300',
    fullBarDamage: '120' },
  { dps: '26',
    name: 'DISCHARGE',
    type: 'ELECTRIC',
    energy: '33',
    power: '65',
    duration: '2,500',
    fullBarDamage: '195' },
  { dps: '25.86',
    name: 'SIGNAL BEAM',
    type: 'BUG',
    energy: '50',
    power: '75',
    duration: '2,900',
    fullBarDamage: '150' },
  { dps: '25',
    name: 'THUNDER PUNCH',
    type: 'ELECTRIC',
    energy: '33',
    power: '45',
    duration: '1,800',
    fullBarDamage: '135' },
  { dps: '25',
    name: 'FIRE PUNCH',
    type: 'FIRE',
    energy: '33',
    power: '55',
    duration: '2,200',
    fullBarDamage: '165' },
  { dps: '25',
    name: 'DRAGON PULSE',
    type: 'DRAGON',
    energy: '50',
    power: '90',
    duration: '3,600',
    fullBarDamage: '180' },
  { dps: '25',
    name: 'BRICK BREAK',
    type: 'FIGHTING',
    energy: '33',
    power: '40',
    duration: '1,600',
    fullBarDamage: '120' },
  { dps: '25',
    name: 'BONE CLUB',
    type: 'GROUND',
    energy: '33',
    power: '40',
    duration: '1,600',
    fullBarDamage: '120' },
  { dps: '25',
    name: 'MAGNET BOMB',
    type: 'STEEL',
    energy: '33',
    power: '70',
    duration: '2,800',
    fullBarDamage: '210' },
  { dps: '24.32',
    name: 'BUG BUZZ',
    type: 'BUG',
    energy: '50',
    power: '90',
    duration: '3,700',
    fullBarDamage: '180' },
  { dps: '24.24',
    name: 'GYRO BALL',
    type: 'STEEL',
    energy: '50',
    power: '80',
    duration: '3,300',
    fullBarDamage: '160' },
  { dps: '24.07',
    name: 'PSYSHOCK',
    type: 'PSYCHIC',
    energy: '33',
    power: '65',
    duration: '2,700',
    fullBarDamage: '195' },
  { dps: '23.91',
    name: 'MUD BOMB',
    type: 'GROUND',
    energy: '33',
    power: '55',
    duration: '2,300',
    fullBarDamage: '165' },
  { dps: '23.81',
    name: 'ROCK BLAST',
    type: 'ROCK',
    energy: '33',
    power: '50',
    duration: '2,100',
    fullBarDamage: '150' },
  { dps: '23.81',
    name: 'SLUDGE',
    type: 'POISON',
    energy: '33',
    power: '50',
    duration: '2,100',
    fullBarDamage: '150' },
  { dps: '23.68',
    name: 'BUBBLE BEAM',
    type: 'WATER',
    energy: '33',
    power: '45',
    duration: '1,900',
    fullBarDamage: '135' },
  { dps: '23.53',
    name: 'SHADOW PUNCH',
    type: 'GHOST',
    energy: '33',
    power: '40',
    duration: '1,700',
    fullBarDamage: '120' },
  { dps: '23.08',
    name: 'ENERGY BALL',
    type: 'GRASS',
    energy: '50',
    power: '90',
    duration: '3,900',
    fullBarDamage: '180' },
  { dps: '23.08',
    name: 'MIRROR COAT',
    type: 'PSYCHIC',
    energy: '50',
    power: '60',
    duration: '2,600',
    fullBarDamage: '120' },
  { dps: '23.08',
    name: 'NIGHT SHADE',
    type: 'GHOST',
    energy: '50',
    power: '60',
    duration: '2,600',
    fullBarDamage: '120' },
  { dps: '23.08',
    name: 'DRAINING KISS',
    type: 'FAIRY',
    energy: '50',
    power: '60',
    duration: '2,600',
    fullBarDamage: '120' },
  { dps: '22.92',
    name: 'AERIAL ACE',
    type: 'FLYING',
    energy: '33',
    power: '55',
    duration: '2,400',
    fullBarDamage: '165' },
  { dps: '22.86',
    name: 'BULLDOZE',
    type: 'GROUND',
    energy: '50',
    power: '80',
    duration: '3,500',
    fullBarDamage: '160' },
  { dps: '22.73',
    name: 'PSYSTRIKE',
    type: 'PSYCHIC',
    energy: '50',
    power: '100',
    duration: '4,400',
    fullBarDamage: '200' },
  { dps: '22.73',
    name: 'NIGHT SLASH',
    type: 'DARK',
    energy: '33',
    power: '50',
    duration: '2,200',
    fullBarDamage: '150' },
  { dps: '22.54',
    name: 'AURORA BEAM',
    type: 'ICE',
    energy: '50',
    power: '80',
    duration: '3,550',
    fullBarDamage: '160' },
  { dps: '22.22',
    name: 'AIR CUTTER',
    type: 'FLYING',
    energy: '50',
    power: '60',
    duration: '2,700',
    fullBarDamage: '120' },
  { dps: '22.22',
    name: 'FLAME WHEEL',
    type: 'FIRE',
    energy: '50',
    power: '60',
    duration: '2,700',
    fullBarDamage: '120' },
  { dps: '21.88',
    name: 'ROCK TOMB',
    type: 'ROCK',
    energy: '50',
    power: '70',
    duration: '3,200',
    fullBarDamage: '140' },
  { dps: '21.88',
    name: 'WATER PULSE',
    type: 'WATER',
    energy: '50',
    power: '70',
    duration: '3,200',
    fullBarDamage: '140' },
  { dps: '21.88',
    name: 'PSYBEAM',
    type: 'PSYCHIC',
    energy: '50',
    power: '70',
    duration: '3,200',
    fullBarDamage: '140' },
  { dps: '21.88',
    name: 'CRUNCH',
    type: 'DARK',
    energy: '33',
    power: '70',
    duration: '3,200',
    fullBarDamage: '210' },
  { dps: '21.74',
    name: 'OMINOUS WIND',
    type: 'GHOST',
    energy: '33',
    power: '50',
    duration: '2,300',
    fullBarDamage: '150' },
  { dps: '21.62',
    name: 'SCALD',
    type: 'WATER',
    energy: '50',
    power: '80',
    duration: '3,700',
    fullBarDamage: '160' },
  { dps: '21.62',
    name: 'HORN ATTACK',
    type: 'NORMAL',
    energy: '33',
    power: '40',
    duration: '1,850',
    fullBarDamage: '120' },
  { dps: '21.43',
    name: 'SWIFT',
    type: 'NORMAL',
    energy: '50',
    power: '60',
    duration: '2,800',
    fullBarDamage: '120' },
  { dps: '21.28',
    name: 'DIG',
    type: 'GROUND',
    energy: '50',
    power: '100',
    duration: '4,700',
    fullBarDamage: '200' },
  { dps: '21.05',
    name: 'LOW SWEEP',
    type: 'FIGHTING',
    energy: '33',
    power: '40',
    duration: '1,900',
    fullBarDamage: '120' },
  { dps: '21.05',
    name: 'HEART STAMP',
    type: 'PSYCHIC',
    energy: '33',
    power: '40',
    duration: '1,900',
    fullBarDamage: '120' },
  { dps: '20.69',
    name: 'WRAP',
    type: 'NORMAL',
    energy: '33',
    power: '60',
    duration: '2,900',
    fullBarDamage: '180' },
  { dps: '20.59',
    name: 'POISON FANG',
    type: 'POISON',
    energy: '33',
    power: '35',
    duration: '1,700',
    fullBarDamage: '105' },
  { dps: '20',
    name: 'ANCIENT POWER',
    type: 'ROCK',
    energy: '33',
    power: '70',
    duration: '3,500',
    fullBarDamage: '210' },
  { dps: '20',
    name: 'SAND TOMB',
    type: 'GROUND',
    energy: '50',
    power: '80',
    duration: '4,000',
    fullBarDamage: '160' },
  { dps: '20',
    name: 'HYDRO PUMP BLASTOISE',
    type: 'WATER',
    energy: '100',
    power: '90',
    duration: '4,500',
    fullBarDamage: '90' },
  { dps: '18.92',
    name: 'SILVER WIND',
    type: 'BUG',
    energy: '33',
    power: '70',
    duration: '3,700',
    fullBarDamage: '210' },
  { dps: '18.42',
    name: 'FLAME CHARGE',
    type: 'FIRE',
    energy: '33',
    power: '70',
    duration: '3,800',
    fullBarDamage: '210' },
  { dps: '18.42',
    name: 'VICE GRIP',
    type: 'NORMAL',
    energy: '33',
    power: '35',
    duration: '1,900',
    fullBarDamage: '105' },
  { dps: '18.18',
    name: 'ICY WIND',
    type: 'ICE',
    energy: '33',
    power: '60',
    duration: '3,300',
    fullBarDamage: '180' },
  { dps: '17.95',
    name: 'DISARMING VOICE',
    type: 'FAIRY',
    energy: '33',
    power: '70',
    duration: '3,900',
    fullBarDamage: '210' },
  { dps: '17.31',
    name: 'AQUA JET',
    type: 'WATER',
    energy: '33',
    power: '45',
    duration: '2,600',
    fullBarDamage: '135' },
  { dps: '17.24',
    name: 'SHADOW SNEAK',
    type: 'GHOST',
    energy: '33',
    power: '50',
    duration: '2,900',
    fullBarDamage: '150' },
  { dps: '16.07',
    name: 'TWISTER',
    type: 'DRAGON',
    energy: '33',
    power: '45',
    duration: '2,800',
    fullBarDamage: '135' },
  { dps: '15.91',
    name: 'STRUGGLE',
    type: 'NORMAL',
    energy: '0',
    power: '35',
    duration: '2,200',
    fullBarDamage: '3500' },
  { dps: '12.82',
    name: 'GIGA DRAIN',
    type: 'GRASS',
    energy: '100',
    power: '50',
    duration: '3,900',
    fullBarDamage: '50' },
  { dps: '10.64',
    name: 'SCALD BLASTOISE',
    type: 'WATER',
    energy: '100',
    power: '50',
    duration: '4,700',
    fullBarDamage: '50' },
  { dps: '9.62',
    name: 'MEGA DRAIN',
    type: 'GRASS',
    energy: '50',
    power: '25',
    duration: '2,600',
    fullBarDamage: '50' },
  { dps: '8.93',
    name: 'PARABOLIC CHARGE',
    type: 'ELECTRIC',
    energy: '50',
    power: '25',
    duration: '2,800',
    fullBarDamage: '50' },
  { dps: '8.62',
    name: 'WRAP PINK',
    type: 'NORMAL',
    energy: '33',
    power: '25',
    duration: '2,900',
    fullBarDamage: '75' },
  { dps: '8.62',
    name: 'WRAP GREEN',
    type: 'NORMAL',
    energy: '33',
    power: '25',
    duration: '2,900',
    fullBarDamage: '75' }];

ReferenceMoves.setMoves = function(poke){
  poke.possibleFM.forEach(function(pFMove, pIndex, ar){
     ReferenceMoves.list.forEach(function(rMove){
       if (pFMove === rMove.name){
           ar[pIndex] = rMove;
       }
     });
  });
  poke.possibleCM.forEach(function(pCMove, pIndex, ar){
     ReferenceMoves.list.forEach(function(rMove){
       if (pCMove === rMove.name){
           ar[pIndex] = rMove;
       }
     });
  });
}

module.exports = ReferenceMoves;
